// Car meshes, shared driver state, configurable training placement, and vehicle-local dynamics state.
const colors=[0x55dbea,0xff7d88,0xffd166,0xc8a5ff,0x72e0a6,0xffa45b,0x7fa8ff,0xf28ee6,0xb7dc5d,0xe7e7e7];
function createCarMesh(color){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(1.55,.45,3),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.12}));body.position.y=.48;body.castShadow=true;g.add(body);const cabin=new THREE.Mesh(new THREE.BoxGeometry(1.18,.42,1.35),new THREE.MeshStandardMaterial({color:0x202b34,roughness:.25}));cabin.position.set(0,.86,.12);cabin.castShadow=true;g.add(cabin);const nose=new THREE.Mesh(new THREE.BoxGeometry(1.25,.18,.55),new THREE.MeshStandardMaterial({color:0xf0f4f6}));nose.position.set(0,.58,-1.35);g.add(nose);for(const sx of[-.72,.72])for(const sz of[-.92,.92]){const wheel=new THREE.Mesh(new THREE.BoxGeometry(.18,.38,.62),new THREE.MeshStandardMaterial({color:0x101214}));wheel.position.set(sx,.28,sz);g.add(wheel)}return g}
function trackHeading(i){const t=tangents[mod(i,TRACK_N)];return Math.atan2(t.z,t.x)}
function nearestTrackPositionFor(car){let bestSegment=car.trackIndex,bestD=Infinity,bestT=0;for(let off=-16;off<=16;off++){const i=mod(car.trackIndex+off,TRACK_N),j=mod(i+1,TRACK_N),a=track[i],b=track[j],sx=b.x-a.x,sz=b.z-a.z,len2=sx*sx+sz*sz,t=len2>1e-9?clamp(((car.x-a.x)*sx+(car.z-a.z)*sz)/len2,0,1):0,px=a.x+sx*t,pz=a.z+sz*t,dx=car.x-px,dz=car.z-pz,d=dx*dx+dz*dz;if(d<bestD){bestD=d;bestSegment=i;bestT=t}}const next=mod(bestSegment+1,TRACK_N),index=bestT>.5?next:bestSegment,arc=trackLength>0?mod((trackDistance[bestSegment]??0)+(segLen[bestSegment]??avgSeg)*bestT,trackLength):0;car.trackIndex=index;return{index,segmentIndex:bestSegment,t:bestT,distance:Math.sqrt(bestD),arc}}
function nearestIndexFor(car){const near=nearestTrackPositionFor(car);return{index:near.index,distance:near.distance}}
function progressDelta(oldI,newI){let d=(trackDistance[newI]??0)-(trackDistance[oldI]??0);if(d>trackLength/2)d-=trackLength;if(d<-trackLength/2)d+=trackLength;return d}
function progressArcDelta(oldArc,newArc){let d=(Number(newArc)||0)-(Number(oldArc)||0);if(d>trackLength/2)d-=trackLength;if(d<-trackLength/2)d+=trackLength;return d}
function headingAlignment(car,index=car.trackIndex){const t=tangents[mod(index,TRACK_N)];return t?clamp(Math.cos(car.heading)*t.x+Math.sin(car.heading)*t.z,-1,1):1}
function distanceFromTrack(car){const q=track[car.trackIndex];return q?Math.hypot(car.x-q.x,car.z-q.z):Infinity}
function surfaceHeightForCar(car){if(activeTrackId!=='figure8')return 0;const q=track[car.trackIndex];if(!q)return 0;return distanceFromTrack(car)<=HALF_WIDTH+SHOULDER_WIDTH?q.y:0}
const drivers=[];
for(let i=0;i<DRIVER_COUNT;i++){const mesh=createCarMesh(colors[i%colors.length]);scene.add(mesh);drivers.push({id:i,mesh,x:0,z:0,heading:0,vx:0,vz:0,speed:0,forwardSpeed:0,lateralSpeed:0,yawRate:0,steerAngle:0,slipAngle:0,lateralAccel:0,longitudinalAccel:0,tireScrub:0,gripUse:0,gear:1,rpm:VEHICLE_IDLE_RPM,shiftTimer:0,damage:0,trackIndex:0,lastTrackIndex:0,trackArc:0,actionSteer:0,actionThrottle:0,pendingReward:0,pendingDone:false,offTime:0,stuckTime:0,lap:0,nextLapProgress:0,lapStartedAt:0,lastLapTime:0,raceStartOffset:0,episodeProgress:0,episodeNetProgress:0,episodePeakProgress:0,totalProgress:0,episodeReward:0,totalReward:0,collisions:0,collisionCooldown:0,directionAlignment:1,surface:'road',rollout:[],lastObs:null,lastForward:null,lastAction:7,lastValue:0,lastLogp:0,lastProb:0,lastEntropy:0,lastTemperature:1.35,latestRGBA:null,raceStatus:'racing',finishTime:null,finishPlace:null,lastRank:null,overtakes:0})}
function syncCarMesh(car){car.mesh.position.set(car.x,surfaceHeightForCar(car),car.z);car.mesh.rotation.y=-car.heading-Math.PI/2}
function gridSpawnPose(slot,extraRow=0){const column=slot%2,row=Math.floor(slot/2)+extraRow,rowMeters=15,gridLead=trackStepsForDistance(36),rowSpacing=trackStepsForDistance(rowMeters),base=mod(finishIndex+gridLead-row*rowSpacing,TRACK_N),q=track[base],n=normals[base],lane=(column===0?-1:1)*1.8;return{base,x:q.x+n.x*lane,z:q.z+n.z*lane,heading:trackHeading(base),raceStartOffset:-row*rowMeters}}
function staggeredSpawnPose(slot,extraOffset=0){const count=Math.max(1,activeDriverCount()),base=mod(finishIndex+Math.round(slot*TRACK_N/count)+trackStepsForDistance(extraOffset*22),TRACK_N),q=track[base];return{base,x:q.x,z:q.z,heading:trackHeading(base),raceStartOffset:0}}
function spawnPose(slot,extra=0){return sim.mode==='learn'&&sim.trainingStaggered?staggeredSpawnPose(slot,extra):gridSpawnPose(slot,extra)}
function resetDriver(car,slot=0,avoidTraffic=true){
  let pose=spawnPose(slot,0);if(avoidTraffic){for(let attempt=0;attempt<10;attempt++){const candidate=spawnPose(slot,attempt),blocked=activeDrivers().some(other=>other!==car&&other.mesh.visible&&Math.hypot(other.x-candidate.x,other.z-candidate.z)<4.2);pose=candidate;if(!blocked)break}}
  car.x=pose.x;car.z=pose.z;car.heading=pose.heading;car.damage=0;car.trackIndex=pose.base;car.lastTrackIndex=pose.base;car.trackArc=trackDistance[pose.base]??0;car.actionSteer=0;car.actionThrottle=0;vehicleResetMotion(car,3.5);car.pendingReward=0;car.pendingDone=false;car.offTime=0;car.stuckTime=0;car.lap=0;car.nextLapProgress=trackLength;car.lapStartedAt=sim.simClock;car.lastLapTime=0;car.raceStartOffset=pose.raceStartOffset;car.episodeProgress=0;car.episodeNetProgress=0;car.episodePeakProgress=0;car.episodeReward=0;car.collisionCooldown=0;car.directionAlignment=1;car.surface='road';car.lastObs=null;car.lastForward=null;car.lastEntropy=0;car.lastTemperature=sim.temperature;car.lastRank=null;car.raceStatus='racing';car.finishTime=null;car.finishPlace=null;car.mesh.visible=true;syncCarMesh(car)
}
function deactivateDriver(car){vehicleStopMotion(car);car.actionSteer=0;car.actionThrottle=0;car.pendingReward=0;car.pendingDone=false;car.rollout=[];car.lastObs=null;car.lastForward=null;car.mesh.visible=false;car.raceStatus='inactive'}
function resetGrid(){const count=activeDriverCount();drivers.forEach((c,i)=>{if(i<count)resetDriver(c,i,false);else deactivateDriver(c)});if(sim.selected>=count)sim.selected=0}
