// Explicit learning/race mode setup and frozen-policy evaluation races.
function discardPartialRollout(reason=''){drivers.forEach(c=>{c.rollout=[];c.lastObs=null;c.lastForward=null;c.pendingReward=0;c.pendingDone=false});sim.experience=0;sim.physicsAcc=0;sim.decisionAcc=0;resetBatchTelemetry();if(reason)log(reason)}
function raceResults(){return activeDrivers().map(c=>({driver:c.id+1,place:c.finishPlace,time:c.finishTime,status:c.raceStatus}))}
function raceResultsText(){const cars=activeDrivers(),placed=cars.filter(c=>c.finishPlace!=null).sort((a,b)=>a.finishPlace-b.finishPlace),dnfs=cars.filter(c=>c.raceStatus==='dnf');if(!placed.length&&!dnfs.length)return sim.raceFinished?'Race ready':`Race in progress · ${sim.raceLaps} laps · ${sim.raceTime.toFixed(1)} s`;const parts=placed.map(c=>`P${c.finishPlace} Driver ${c.id+1} ${c.finishTime.toFixed(1)}s`);dnfs.forEach(c=>parts.push(`Driver ${c.id+1} DNF`));return parts.join(' · ')}
function chooseSpectatorRacer(){const current=drivers[sim.selected];if(current&&current.raceStatus==='racing')return;const next=activeDrivers().find(c=>c.raceStatus==='racing');if(next)sim.selected=next.id}
function prepareRaceGrid(){buildTrack(sim.raceTrackId,false);resetGrid();primeObservations();activeDrivers().forEach(c=>{c.lap=0;c.raceStatus='ready';c.finishTime=null;c.finishPlace=null;c.mesh.visible=true});activeDrivers().forEach(chooseAction)}
function markRaceFinished(car){if(car.raceStatus!=='racing')return;car.raceStatus='finished';car.finishTime=sim.raceTime;car.finishPlace=++sim.racePlaces;vehicleStopMotion(car);car.actionThrottle=0;car.actionSteer=0;const q=track[finishIndex],n=normals[finishIndex],t=tangents[finishIndex];car.x=q.x+n.x*(HALF_WIDTH+SHOULDER_WIDTH+2)+t.x*((car.finishPlace-1)*2.1);car.z=q.z+n.z*(HALF_WIDTH+SHOULDER_WIDTH+2)+t.z*((car.finishPlace-1)*2.1);car.heading=trackHeading(finishIndex);syncCarMesh(car);log(`Race: Driver ${car.id+1} finished P${car.finishPlace} in ${car.finishTime.toFixed(1)} s.`);chooseSpectatorRacer();checkRaceComplete()}
function markRaceDNF(car){if(car.raceStatus!=='racing')return;car.raceStatus='dnf';vehicleStopMotion(car);car.mesh.visible=false;log(`Race: Driver ${car.id+1} DNF.`);chooseSpectatorRacer();checkRaceComplete()}
function checkRaceComplete(){if(sim.mode!=='race'||sim.raceFinished||activeDrivers().some(c=>c.raceStatus==='racing'))return;sim.raceFinished=true;sim.running=false;$('raceResult').innerHTML=`<strong>Race complete on ${escapeHtml(TRACK_DEFS[activeTrackId].name)}.</strong> ${escapeHtml(raceResultsText())}`;log(`Evaluation race complete on ${TRACK_DEFS[activeTrackId].name}: ${raceResultsText()}`);if(typeof sessionRecordRace==='function')sessionRecordRace(activeTrackId,sim.raceLaps,raceResults());if(typeof scheduleSessionSave==='function')scheduleSessionSave(150);updateUI()}
function enterRaceMode(){if(sim.learning)return;const lost=sim.mode==='learn'&&sim.experience>0;sim.running=false;sim.mode='race';sim.headless=false;sim.raceTrackId=$('raceTrackSelect').value in TRACK_DEFS?$('raceTrackSelect').value:sim.raceTrackId;sim.raceLaps=Number($('raceLaps').value);sim.raceTime=0;sim.racePlaces=0;sim.raceFinished=true;discardPartialRollout(lost?'Switched to Evaluation Race; unfinished learning batch discarded.':'Evaluation Race mode selected.');prepareRaceGrid();$('raceResult').innerHTML=`<strong>Evaluation Race ready.</strong> ${escapeHtml(activeBrain()?.name||'Current brain')} at update ${sim.update} · ${escapeHtml(TRACK_DEFS[sim.raceTrackId].name)} · ${sim.raceLaps} laps. Press Start evaluation race.`;if(typeof scheduleSessionSave==='function')scheduleSessionSave();updateUI()}
function startEvaluationRace(){if(sim.learning)return;if(sim.mode!=='race')enterRaceMode();sim.running=false;sim.headless=false;sim.raceTrackId=$('raceTrackSelect').value in TRACK_DEFS?$('raceTrackSelect').value:'mixed';sim.raceLaps=Number($('raceLaps').value);sim.raceTime=0;sim.racePlaces=0;sim.raceFinished=false;discardPartialRollout();buildTrack(sim.raceTrackId,false);resetGrid();primeObservations();activeDrivers().forEach(c=>{c.lap=0;c.raceStatus='racing';c.finishTime=null;c.finishPlace=null;c.mesh.visible=true});activeDrivers().forEach(chooseAction);sim.running=true;$('raceResult').innerHTML=`<strong>Evaluation race running:</strong> ${sim.raceLaps} laps on ${TRACK_DEFS[activeTrackId].name}. Four physical cars; policy frozen; deterministic actions; no backprop.`;log(`Started ${sim.raceLaps}-lap ${TRACK_DEFS[activeTrackId].name} evaluation race with ${activeBrain()?.name||'current brain'} at update ${sim.update}.`);updateUI()}
function enterLearningMode(){if(sim.learning)return;if(sim.mode==='learn'){updateUI();return}const id=sim.trackMode in TRACK_DEFS?sim.trackMode:'mixed';sim.running=false;sim.mode='learn';sim.raceFinished=false;discardPartialRollout(`Learning mode selected on ${trackVariantName(id,sim.trackMirror)}.`);buildTrack(id,sim.trackMirror);resetGrid();primeObservations();sim.experiencesSinceGridReset=0;activeDrivers().forEach(c=>{c.lap=0;c.mesh.visible=true});activeDrivers().forEach(chooseAction);$('raceResult').textContent=`Learning setup ready for ${activeBrain()?.name||'current brain'} on ${trackVariantName(id,sim.trackMirror)} with ${activeDriverCount()} training car${activeDriverCount()===1?'':'s'}. PPO updates every ${sim.ppoBatchTarget} experiences.`;updateUI()}
function changeTrackMode(){if(sim.learning){$('trackSelect').value=sim.trackMode;return}const id=$('trackSelect').value in TRACK_DEFS?$('trackSelect').value:'mixed';sim.trackMode=id;sim.adaptiveResetInterval=1;sim.experiencesSinceGridReset=0;sim.experiencesSinceTrackSwitch=0;resetRecentTelemetry();if(sim.mode==='race'){log(`Training track set to ${trackVariantName(id,sim.trackMirror)} for the next learning session.`);if(typeof sessionRecordTrackChange==='function')sessionRecordTrackChange(id);scheduleSessionSave();return}const wasRunning=sim.running;sim.raceFinished=false;discardPartialRollout(`Training track changed to ${trackVariantName(id,sim.trackMirror)}; partial PPO batch discarded and cars clean-started.`);buildTrack(id,sim.trackMirror);resetGrid();primeObservations();activeDrivers().forEach(c=>{c.lap=0;c.mesh.visible=true});activeDrivers().forEach(chooseAction);sim.running=wasRunning;$('raceResult').textContent=`Training track: ${trackVariantName(id,sim.trackMirror)}. Brain preserved; recent-driving chart restarted for this circuit.`;if(typeof sessionRecordTrackChange==='function')sessionRecordTrackChange(id);scheduleSessionSave();updateUI()}
function changeRaceTrackMode(){sim.raceTrackId=$('raceTrackSelect').value in TRACK_DEFS?$('raceTrackSelect').value:'mixed';if(sim.mode!=='race')return;if(sim.running&&!sim.raceFinished){log(`Next evaluation track set to ${TRACK_DEFS[sim.raceTrackId].name}; current race continues.`);return}sim.running=false;sim.raceFinished=true;sim.raceTime=0;sim.racePlaces=0;prepareRaceGrid();$('raceResult').innerHTML=`<strong>Evaluation Race ready.</strong> ${TRACK_DEFS[sim.raceTrackId].name} · ${sim.raceLaps} laps. Press Start evaluation race.`;updateUI()}
