// Fixed-step scheduler, explicit mode controls, session/brain commands, and presentation-only render throttling.
let uiAcc=0,renderAcc=0;
function headlessActive(){return sim.headless&&sim.mode==='learn'}
function advanceSimulation(simSeconds){const FIXED=1/60,MAX_STEPS=900,MAX_BACKLOG=2.5;sim.physicsAcc=Math.min(MAX_BACKLOG,sim.physicsAcc+simSeconds);let steps=0;while(sim.physicsAcc+1e-9>=FIXED&&steps++<MAX_STEPS&&sim.running&&!sim.learning){physicsStep(FIXED);if(sim.mode==='learn'){sim.trainingSimSeconds+=FIXED;recordRecentTelemetry(FIXED)}sim.physicsAcc-=FIXED;sim.decisionAcc+=FIXED;if(sim.decisionAcc+1e-9>=DECISION_DT&&!sim.learning){sim.decisionAcc-=DECISION_DT;decisionStep()}}}
function spectatorPeriod(){if(headlessActive())return Infinity;if(sim.mode!=='learn')return 0;if(sim.speed>=50)return .25;if(sim.speed>=10)return .10;return 0}
function dashboardPeriod(){if(headlessActive())return 1;if(sim.mode==='learn'&&sim.speed>=50)return .60;if(sim.mode==='learn'&&sim.speed>=10)return .30;return .16}
function renderSpectator(){updateMainCamera();renderer.setRenderTarget(null);const selectedMesh=drivers[sim.selected].mesh,hideOwnCar=sim.cameraMode==='pov',wasVisible=selectedMesh.visible,savedFog=scene.fog;if(hideOwnCar)selectedMesh.visible=false;if(sim.cameraMode==='overview')scene.fog=null;try{renderer.render(scene,mainCamera)}finally{scene.fog=savedFog;if(hideOwnCar)selectedMesh.visible=wasVisible}}
function animate(now){requestAnimationFrame(animate);const rawDt=Math.max(0,(now-sim.lastTime)/1000),realDt=Math.min(.05,rawDt);sim.lastTime=now;if(sim.mode==='learn'&&(sim.running||sim.learning))sim.trainingWallSeconds+=rawDt;if(sim.running&&!sim.learning)advanceSimulation(realDt*sim.speed);const headless=headlessActive(),period=spectatorPeriod();container.classList.toggle('fast-paused',headless);renderAcc+=rawDt;if(!headless&&(period===0||renderAcc>=period)){renderAcc=0;renderSpectator()}if(now-sim.measureReal>=1000){const realSeconds=(now-sim.measureReal)/1000;sim.achievedSpeed=(sim.simClock-sim.measureSim)/Math.max(.001,realSeconds);sim.measureReal=now;sim.measureSim=sim.simClock}updateAudio();uiAcc+=rawDt;if(uiAcc>=dashboardPeriod()){uiAcc=0;updateUI()}}

async function resetActiveBrain(){if(sim.learning)return;const brain=activeBrain();if(!brain)return;if(!confirm(`Reset ${brain.name}? This recreates its initial weights and stochastic streams from seed ${brainExperimentSeed(brain)}, then clears its training/race history. The current training-environment settings are preserved.`))return;const config={...brain.config},track=sim.trackMode,reset=sim.resetMode,ppo=ppoSettingsSnapshot(),environment=trainingEnvironmentSnapshot(),seed=brainExperimentSeed(brain);setupFreshBrainRuntime(config,track,reset,seed,environment);applyPpoSettings(ppo);syncPpoControls();brain.experiment={seed,seededFromStart:true,trackLayoutVersion:TRACK_LAYOUT_VERSION,vehicleDynamicsVersion:VEHICLE_DYNAMICS_VERSION,vehicleObservationVersion:VEHICLE_OBSERVATION_VERSION,rewardContractVersion:REWARD_CONTRACT_VERSION,trainerVersion:TRAINER_VERSION};brain.net=networkSnapshot();brain.training=trainingStateSnapshot();brain.trainingSegments=[];brain.races=[];brain.updatedAt=nowIso();const env=`T${TRACK_LAYOUT_VERSION}/D${VEHICLE_DYNAMICS_VERSION}/O${VEHICLE_OBSERVATION_VERSION}/R${REWARD_CONTRACT_VERSION}/A${TRAINER_VERSION}`;sessionRecordEvent('brain-reset',`Reset ${brain.name} to seed ${seed} on ${env} with fresh deterministic weights.`,{brainId:brain.id,config,ppo,environment,seed,trackLayoutVersion:TRACK_LAYOUT_VERSION,vehicleDynamicsVersion:VEHICLE_DYNAMICS_VERSION,vehicleObservationVersion:VEHICLE_OBSERVATION_VERSION,rewardContractVersion:REWARD_CONTRACT_VERSION,trainerVersion:TRAINER_VERSION});await saveLabSessionNow();$('trainingLog').innerHTML='';log(`${brain.name} reset from seed ${seed} on ${env}.`);$('raceResult').textContent=`${brain.name} reset. Learning is paused on ${trackVariantName(sim.trackMode,sim.trackMirror)}.`;updateUI()}

function syncPpoControls(){if($('ppoBatchSelect'))$('ppoBatchSelect').value=String(sim.ppoBatchTarget);if($('ppoEpochSelect'))$('ppoEpochSelect').value=String(sim.ppoEpochs);if($('ppoLearningRateSelect'))$('ppoLearningRateSelect').value=String(sim.ppoLearningRate);if($('ppoClipSelect'))$('ppoClipSelect').value=String(sim.ppoClip)}
function changePpoSettings(){if(sim.learning){syncPpoControls();return}const next=normalizedPpoSettings({batchTarget:$('ppoBatchSelect').value,epochs:$('ppoEpochSelect').value,learningRate:$('ppoLearningRateSelect').value,clip:$('ppoClipSelect').value});if(sim.experience>0)discardPartialRollout('PPO settings changed; unfinished experience batch discarded.');applyPpoSettings(next);syncPpoControls();const text=`PPO settings: ${sim.ppoBatchTarget} experiences · ${sim.ppoEpochs} passes · lr ${sim.ppoLearningRate} · clip ${sim.ppoClip}.`;if(typeof syncActiveBrainFromRuntime==='function')syncActiveBrainFromRuntime(false);log(text);if(typeof sessionRecordEvent==='function')sessionRecordEvent('ppo-settings',text,{brainId:activeBrain()?.id||null,...ppoSettingsSnapshot()});else scheduleSessionSave();updateUI()}
function syncTrainingEnvironmentControls(){if($('trainingCarCount'))$('trainingCarCount').value=String(normalizedTrainingDriverCount(sim.trainingDriverCount));if($('trainingCarCollisions'))$('trainingCarCollisions').checked=!!sim.trainingCarCollisions;if($('trainingStaggered'))$('trainingStaggered').checked=!!sim.trainingStaggered;if($('observationCameraMode'))$('observationCameraMode').value=normalizedObservationCameraMode(sim.observationCameraMode);if($('trackMirror'))$('trackMirror').checked=!!sim.trackMirror;if($('autoTrackSwitch'))$('autoTrackSwitch').checked=!!sim.autoTrackSwitch}
function trainingEnvironmentText(){return`${sim.trainingDriverCount} car${sim.trainingDriverCount===1?'':'s'} · ${sim.observationCameraMode==='overhead'?'overhead neural view':'POV neural view'} · ${sim.trainingCarCollisions?'physical collisions':'ghost traffic'} · ${sim.trainingStaggered?'staggered':'grid'} · ${sim.trackMirror?'mirrored':'normal'} · ${sim.autoTrackSwitch?`rotate every ${Number(sim.trackSwitchEveryExperiences).toLocaleString()} exp`:'fixed track'}`}
function changeTrainingEnvironment(){
  if(sim.learning){syncTrainingEnvironmentControls();return}
  const next={trainingDriverCount:normalizedTrainingDriverCount($('trainingCarCount').value),trainingCarCollisions:$('trainingCarCollisions').checked,trainingStaggered:$('trainingStaggered').checked,observationCameraMode:normalizedObservationCameraMode($('observationCameraMode').value),trackMirror:$('trackMirror').checked,autoTrackSwitch:$('autoTrackSwitch').checked,trackSwitchEveryExperiences:TRACK_SWITCH_EXPERIENCES},before=JSON.stringify(trainingEnvironmentSnapshot());if(JSON.stringify(next)===before){syncTrainingEnvironmentControls();return}
  const wasRunning=sim.running;sim.running=false;discardPartialRollout(sim.experience>0?'Training environment changed; unfinished experience batch discarded so one PPO update never mixes environments.':'');applyTrainingEnvironment(next);sim.experiencesSinceGridReset=0;sim.adaptiveResetInterval=1;resetRecentTelemetry();syncTrainingEnvironmentControls();
  if(sim.mode==='learn'){buildTrack(sim.trackMode,sim.trackMirror);resetGrid();primeObservations();activeDrivers().forEach(chooseAction);sim.running=wasRunning}else sim.running=wasRunning;
  const text=`Training environment: ${trainingEnvironmentText()}.`;log(text);if(typeof sessionRecordEvent==='function')sessionRecordEvent('training-environment',text,{brainId:activeBrain()?.id||null,...trainingEnvironmentSnapshot()});else scheduleSessionSave();updateUI()
}
function setNewBrainSeed(seed=randomExperimentSeed()){const value=normalizeExperimentSeed(seed);if($('seedInput'))$('seedInput').value=String(value);refreshBrainSetupSummary();return value}
function wireControls(){
  $('modeLearnBtn').addEventListener('click',enterLearningMode);$('modeRaceBtn').addEventListener('click',enterRaceMode);
  $('runBtn').addEventListener('click',()=>{if(sim.mode!=='learn')return;if(sim.learning){sim.pauseAfterLearning=true;log('Pause requested; the current backprop update will finish, then learning will remain paused.');updateUI();return}sim.running=!sim.running;const cars=activeDrivers();if(sim.running&&cars.every(c=>c.lastObs===null))cars.forEach(chooseAction);if(!sim.running)scheduleSessionSave(120);updateUI()});
  $('racePauseBtn').addEventListener('click',()=>{if(sim.mode!=='race'||sim.raceFinished)return;sim.running=!sim.running;updateUI()});
  document.querySelectorAll('.speed-btn').forEach(b=>b.addEventListener('click',()=>{sim.speed=Number(b.dataset.speed);document.querySelectorAll('.speed-btn').forEach(x=>x.classList.toggle('active',x===b));log(`Requested simulation speed: ${sim.speed}×. Physics and policy cadence are unchanged.`)}));
  $('headlessBtn').addEventListener('click',()=>{if(sim.mode!=='learn')return;sim.headless=!sim.headless;log(sim.headless?'Headless visuals enabled. Spectator, driver-card and Brain Inspector repainting are paused; training charts remain live.':'Headless visuals disabled. Full live presentation restored.');updateUI()});
  $('cameraSelect').addEventListener('change',()=>{sim.cameraMode=$('cameraSelect').value;$('cameraSelect').blur()});$('soundBtn').addEventListener('click',()=>toggleAudio().catch(error=>log(`Sound failed: ${error.message}`)));
  $('visionSelect').addEventListener('change',refreshBrainSetupSummary);$('networkSelect').addEventListener('change',refreshBrainSetupSummary);$('seedInput').addEventListener('change',()=>setNewBrainSeed($('seedInput').value));$('randomSeedBtn').addEventListener('click',()=>setNewBrainSeed());$('newBrainBtn').addEventListener('click',()=>{if(sim.learning)return;createFreshBrain({visionId:$('visionSelect').value,networkId:$('networkSelect').value},null,$('seedInput').value).then(()=>setNewBrainSeed()).catch(error=>log(`Brain creation failed: ${error.message}`))});
  $('trackSelect').addEventListener('change',changeTrackMode);$('resetMode').addEventListener('change',()=>{if(sim.learning){$('resetMode').value=sim.resetMode;return}const allowed=['adaptive','1','2','4','8','never'];sim.resetMode=allowed.includes($('resetMode').value)?$('resetMode').value:'never';if(sim.resetMode==='adaptive')sim.adaptiveResetInterval=1;sim.experiencesSinceGridReset=0;const multiplier=sim.resetMode==='adaptive'?sim.adaptiveResetInterval:sim.resetMode==='never'?Infinity:Number(sim.resetMode);log(`Clean-start cadence changed to ${sim.resetMode==='adaptive'?`adaptive from ${cleanResetExperienceInterval(multiplier).toLocaleString()} experiences`:sim.resetMode==='never'?'failures only':`every ${cleanResetExperienceInterval(multiplier).toLocaleString()} experiences`}. Current cars continue; countdown restarts.`);scheduleSessionSave();updateUI()});
  for(const id of['trainingCarCount','trainingCarCollisions','trainingStaggered','observationCameraMode','trackMirror','autoTrackSwitch'])$(id).addEventListener('change',changeTrainingEnvironment);
  $('raceTrackSelect').addEventListener('change',changeRaceTrackMode);$('raceLaps').addEventListener('change',()=>{const requested=Number($('raceLaps').value);if(sim.mode==='race'&&!sim.raceFinished){log(`Next evaluation race length set to ${requested} laps; current race remains ${sim.raceLaps} laps.`);return}sim.raceLaps=requested;if(sim.mode==='race'&&!sim.running)$('raceResult').innerHTML=`<strong>Evaluation Race ready.</strong> ${TRACK_DEFS[sim.raceTrackId].name} · ${sim.raceLaps} laps. Press Start evaluation race.`;updateUI()});$('raceBtn').addEventListener('click',startEvaluationRace);
  $('saveBtn').addEventListener('click',exportActiveBrain);$('loadBtn').addEventListener('click',()=>$('loadInput').click());$('loadInput').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{await importBrainData(JSON.parse(await file.text()));log(`Imported brain from ${file.name}.`)}catch(error){log(`Brain import failed: ${error.message}`);$('raceResult').innerHTML=`<strong>Brain import failed.</strong> ${error.message}`}event.target.value=''});
  $('newSessionBtn').addEventListener('click',()=>createNewLabSession({visionId:$('visionSelect').value,networkId:$('networkSelect').value}).catch(error=>log(`New session failed: ${error.message}`)));$('exportAllBtn').addEventListener('click',exportAllSession);$('importAllBtn').addEventListener('click',()=>$('importAllInput').click());$('importAllInput').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{await importSessionData(JSON.parse(await file.text()));log(`Imported complete session from ${file.name}.`)}catch(error){log(`Session import failed: ${error.message}`)}event.target.value=''});
  $('loadSessionBtn').addEventListener('click',()=>loadStoredSession($('sessionPicker').value).catch(error=>log(`Session load failed: ${error.message}`)));$('renameSessionBtn').addEventListener('click',()=>renameLabSession($('sessionNameInput').value).catch(error=>log(`Session rename failed: ${error.message}`)));$('renameBrainBtn').addEventListener('click',()=>renameActiveBrain($('brainNameInput').value).catch(error=>log(`Brain rename failed: ${error.message}`)));$('duplicateBrainBtn').addEventListener('click',()=>duplicateActiveBrain().catch(error=>log(`Brain duplicate failed: ${error.message}`)));
  $('persistStorageBtn').addEventListener('click',()=>requestPersistentStorage().catch(error=>log(`Persistent storage request failed: ${error.message}`)));$('deleteSessionBtn').addEventListener('click',()=>deleteCurrentSession().catch(error=>log(`Session delete failed: ${error.message}`)));$('clearLocalDataBtn').addEventListener('click',()=>clearAllLocalLabData().catch(error=>log(`Local-data clear failed: ${error.message}`)));$('resetBtn').addEventListener('click',()=>resetActiveBrain().catch(error=>log(`Brain reset failed: ${error.message}`)));
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveLabSessionNow()});
}
async function initializeLab(){sim.trackMode='mixed';sim.mode='learn';buildTrack(sim.trackMode,sim.trackMirror);resetBatchTelemetry();resetRecentTelemetry();resetGrid();primeObservations();activeDrivers().forEach(chooseAction);mainCamera.position.set(0,12,45);drivers.forEach(c=>syncCarMesh(c));$('trackSelect').value=sim.trackMode;$('resetMode').value=sim.resetMode;$('raceTrackSelect').value=sim.raceTrackId;$('cameraSelect').value=sim.cameraMode;syncTrainingEnvironmentControls();setNewBrainSeed();wireControls();refreshBrainSetupSummary();await initializeSessionStorage();$('trackSelect').value=sim.trackMode;$('resetMode').value=sim.resetMode;$('raceTrackSelect').value=sim.raceTrackId;$('visionSelect').value=brainConfig.visionId;$('networkSelect').value=brainConfig.networkId;syncPpoControls();syncTrainingEnvironmentControls();refreshBrainSetupSummary();log(`Ready · ${activeBrain()?.name||'active brain'} · ${brainConfigLabel()} · seed ${sim.experimentSeed} · ${trainingEnvironmentText()}.`);sim.lastTime=performance.now();sim.measureReal=sim.lastTime;sim.measureSim=sim.simClock;updateUI();updateBrainInspector(true);animate(performance.now())}
initializeLab().catch(error=>{if(typeof globalThis.showRlRacingError==='function')globalThis.showRlRacingError(error,'initialization');else console.error('POV RL Racing Lab initialization failed.',error)});
