// Browser-local lab sessions: multiple brains, experiment history, IndexedDB autosave, and portable exports.
const SESSION_DB='pov-rl-racing-lab',SESSION_STORE='sessions',SESSION_DB_VERSION=1,LAST_SESSION_KEY='pov-rl-racing-lab:last-session';
let sessionDb=null,labSession=null,storedSessionSummaries=[],sessionSaveTimer=null,sessionStorageStatus='Starting local storage…';
function nowIso(){return new Date().toISOString()}
function activeBrain(){return labSession?.brains?.find(b=>b.id===labSession.activeBrainId)||null}
function trainingStateSnapshot(){return{update:sim.update,totalExperience:sim.totalExperience,temperature:sim.temperature,trackMode:sim.trackMode,resetMode:sim.resetMode,adaptiveResetInterval:sim.adaptiveResetInterval,history:structuredClone(sim.history),trainingWallSeconds:sim.trainingWallSeconds,trainingSimSeconds:sim.trainingSimSeconds,bestRunDistance:sim.bestRunDistance}}
function restoreTrainingState(t={}){sim.pauseAfterLearning=false;sim.update=Number(t.update)||0;sim.totalExperience=Number(t.totalExperience)||0;sim.temperature=clamp(Number(t.temperature)||1.35,.72,1.35);sim.trackMode=t.trackMode in TRACK_DEFS?t.trackMode:'mixed';sim.resetMode=['adaptive','1','2','4','8','never'].includes(String(t.resetMode))?String(t.resetMode):'adaptive';sim.adaptiveResetInterval=[1,2,4,8].includes(Number(t.adaptiveResetInterval))?Number(t.adaptiveResetInterval):1;sim.history=Array.isArray(t.history)?structuredClone(t.history):[];sim.lastMetrics=sim.history.at(-1)||null;sim.trainingWallSeconds=Number(t.trainingWallSeconds)||0;sim.trainingSimSeconds=Number(t.trainingSimSeconds)||0;sim.bestRunDistance=Number(t.bestRunDistance)||Math.max(0,...sim.history.map(x=>Number(x.bestRunDistance)||Number(x.batchBestRunDistance)||0));sim.experience=0;sim.lastLoss=Number(sim.lastMetrics?.loss)||0;sim.updatesSinceGridReset=0;sim.physicsAcc=0;sim.decisionAcc=0}
function resetTrainingState(){sim.pauseAfterLearning=false;sim.update=0;sim.experience=0;sim.totalExperience=0;sim.temperature=1.35;sim.lastLoss=0;sim.history=[];sim.lastMetrics=null;sim.trainingWallSeconds=0;sim.trainingSimSeconds=0;sim.bestRunDistance=0;sim.adaptiveResetInterval=1;sim.updatesSinceGridReset=0;sim.physicsAcc=0;sim.decisionAcc=0;resetBatchTelemetry();resetRecentTelemetry()}
function resetDriversForBrain(){drivers.forEach(c=>{c.rollout=[];c.lastObs=null;c.lastForward=null;c.totalReward=0;c.totalProgress=0;c.lap=0;c.collisions=0;c.overtakes=0;c.latestRGBA=null;c.mesh.visible=true});resetGrid();primeObservations();drivers.forEach(chooseAction)}
function makeBrainRecord(name=`Brain ${(labSession?.brains?.length||0)+1}`,parentId=null){return{id:uid('brain'),name,createdAt:nowIso(),updatedAt:nowIso(),parentId,config:brainConfigSnapshot(),net:networkSnapshot(),training:trainingStateSnapshot(),trainingSegments:[],races:[]}}
function syncActiveBrainFromRuntime(includeNet=true){const brain=activeBrain();if(!brain)return null;brain.config=brainConfigSnapshot();if(includeNet)brain.net=networkSnapshot();brain.training=trainingStateSnapshot();brain.updatedAt=nowIso();return brain}
function sessionRecordEvent(type,text,data={}){if(!labSession)return;labSession.events.push({id:uid('event'),at:nowIso(),type,text,data:structuredClone(data)});if(labSession.events.length>300)labSession.events.splice(0,labSession.events.length-300);labSession.updatedAt=nowIso();scheduleSessionSave()}
function sessionAfterLearningUpdate(metrics){const brain=activeBrain();if(!brain)return;brain.training=trainingStateSnapshot();brain.updatedAt=nowIso();const segments=brain.trainingSegments||(brain.trainingSegments=[]),last=segments.at(-1);if(last&&last.trackId===sim.trackMode&&last.endUpdate===sim.update-1){last.endUpdate=sim.update;last.endExperience=sim.totalExperience;last.bestRunDistance=Math.max(last.bestRunDistance||0,metrics.batchBestRunDistance||0);last.laps=(last.laps||0)+(metrics.laps||0)}else segments.push({trackId:sim.trackMode,startUpdate:sim.update,endUpdate:sim.update,startExperience:Math.max(0,sim.totalExperience-BATCH_TARGET),endExperience:sim.totalExperience,bestRunDistance:metrics.batchBestRunDistance||0,laps:metrics.laps||0});labSession.updatedAt=nowIso();scheduleSessionSave()}
function sessionRecordRace(trackId,laps,results){const brain=activeBrain();if(!brain)return;const record={at:nowIso(),trackId,laps,policyUpdate:sim.update,results:structuredClone(results)};brain.races.push(record);if(brain.races.length>80)brain.races.shift();sessionRecordEvent('race',`Race completed: ${TRACK_DEFS[trackId]?.name||trackId}, ${laps} lap${laps===1?'':'s'}.`,{brainId:brain.id,...record})}
function sessionRecordTrackChange(trackId){const brain=activeBrain();sessionRecordEvent('track',`Training track set to ${TRACK_DEFS[trackId]?.name||trackId}.`,{brainId:brain?.id||null,trackId,update:sim.update})}

function openSessionDb(){if(sessionDb)return Promise.resolve(sessionDb);return new Promise((resolve,reject)=>{const req=indexedDB.open(SESSION_DB,SESSION_DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(SESSION_STORE))db.createObjectStore(SESSION_STORE,{keyPath:'id'})};req.onsuccess=()=>{sessionDb=req.result;resolve(sessionDb)};req.onerror=()=>reject(req.error||new Error('Could not open IndexedDB.'))})}
function dbRequest(mode,work){return openSessionDb().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction(SESSION_STORE,mode),store=tx.objectStore(SESSION_STORE),req=work(store);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);tx.onerror=()=>reject(tx.error)}))}
async function refreshStoredSessionSummaries(){try{const rows=await dbRequest('readonly',s=>s.getAll());storedSessionSummaries=rows.map(x=>({id:x.id,name:x.name,updatedAt:x.updatedAt,brainCount:x.brains?.length||0})).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))}catch{storedSessionSummaries=[]}return storedSessionSummaries}
async function saveLabSessionNow(){if(!labSession)return;try{syncActiveBrainFromRuntime(true);labSession.updatedAt=nowIso();sessionStorageStatus='Saving locally…';if(typeof updateSessionUI==='function')updateSessionUI();await dbRequest('readwrite',s=>s.put(labSession));localStorage.setItem(LAST_SESSION_KEY,labSession.id);sessionStorageStatus=`Saved locally · ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}`;await refreshStoredSessionSummaries();if(typeof updateSessionUI==='function')updateSessionUI()}catch(error){sessionStorageStatus=`Local save failed: ${error.message}`;if(typeof updateSessionUI==='function')updateSessionUI();console.warn('Session autosave failed.',error)}}
function scheduleSessionSave(delay=800){clearTimeout(sessionSaveTimer);sessionStorageStatus='Local changes pending…';sessionSaveTimer=setTimeout(()=>{const run=()=>saveLabSessionNow();if('requestIdleCallback'in globalThis)requestIdleCallback(run,{timeout:1800});else run()},delay);if(typeof updateSessionUI==='function')updateSessionUI()}

function applyBrainRecord(brain){
  sim.running=false;sim.learning=false;sim.mode='learn';sim.headless=false;sim.raceFinished=false;applyBrainConfiguration(brain.config);rebuildPerceptionResources();net=networkFromSnapshot(brain.net);restoreTrainingState(brain.training);resetBatchTelemetry();resetRecentTelemetry();buildTrack(sim.trackMode);resetDriversForBrain();if($('trackSelect'))$('trackSelect').value=sim.trackMode;if($('resetMode'))$('resetMode').value=sim.resetMode;if($('visionSelect'))$('visionSelect').value=brain.config.visionId;if($('networkSelect'))$('networkSelect').value=brain.config.networkId;if($('raceResult'))$('raceResult').textContent=`Loaded ${brain.name}. Learning is paused on ${TRACK_DEFS[sim.trackMode].name}.`;if(typeof refreshBrainSetupSummary==='function')refreshBrainSetupSummary();if(typeof updateUI==='function')updateUI();
}
async function switchActiveBrain(id){if(!labSession||id===labSession.activeBrainId)return;syncActiveBrainFromRuntime(true);const next=labSession.brains.find(b=>b.id===id);if(!next)return;labSession.activeBrainId=id;applyBrainRecord(next);sessionRecordEvent('brain-switch',`Switched to ${next.name}.`,{brainId:id});await saveLabSessionNow()}
function setupFreshBrainRuntime(config,trackId=sim.trackMode,resetMode=sim.resetMode){sim.running=false;sim.mode='learn';sim.headless=false;sim.raceFinished=false;applyBrainConfiguration(config);rebuildPerceptionResources();net=createNetwork();sim.trackMode=trackId in TRACK_DEFS?trackId:'mixed';sim.resetMode=['adaptive','1','2','4','8','never'].includes(String(resetMode))?String(resetMode):'adaptive';resetTrainingState();buildTrack(sim.trackMode);resetDriversForBrain();if($('trackSelect'))$('trackSelect').value=sim.trackMode;if($('resetMode'))$('resetMode').value=sim.resetMode}
async function createFreshBrain(config,name=null){if(!labSession)return;syncActiveBrainFromRuntime(true);const c=normalizedBrainConfig(config),track=sim.trackMode,reset=sim.resetMode;setupFreshBrainRuntime(c,track,reset);const brain=makeBrainRecord(name||`Brain ${labSession.brains.length+1}`);labSession.brains.push(brain);labSession.activeBrainId=brain.id;sessionRecordEvent('brain-create',`Created ${brain.name}: ${brainConfigLabel(c)}.`,{brainId:brain.id,config:c});await saveLabSessionNow();updateUI()}
async function duplicateActiveBrain(){const source=syncActiveBrainFromRuntime(true);if(!source||!labSession)return;const clone=structuredClone(source);clone.id=uid('brain');clone.name=`${source.name} copy`;clone.parentId=source.id;clone.createdAt=clone.updatedAt=nowIso();labSession.brains.push(clone);labSession.activeBrainId=clone.id;applyBrainRecord(clone);sessionRecordEvent('brain-duplicate',`Duplicated ${source.name} as ${clone.name}.`,{brainId:clone.id,parentId:source.id});await saveLabSessionNow()}
async function renameActiveBrain(name){const brain=activeBrain();name=String(name||'').trim();if(!brain||!name)return;brain.name=name;brain.updatedAt=nowIso();sessionRecordEvent('brain-rename',`Active brain renamed to ${name}.`,{brainId:brain.id});await saveLabSessionNow()}
async function renameLabSession(name){name=String(name||'').trim();if(!labSession||!name)return;labSession.name=name;labSession.updatedAt=nowIso();await saveLabSessionNow()}
function newSessionObject(name='Racing Lab Session'){return{format:'pov-rl-racing-lab-session',version:1,id:uid('session'),name,createdAt:nowIso(),updatedAt:nowIso(),activeBrainId:null,brains:[],events:[]}}
async function createNewLabSession(config=brainConfigSnapshot()){if(labSession)await saveLabSessionNow();labSession=newSessionObject(`Session ${new Date().toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}`);setupFreshBrainRuntime(config,'mixed','adaptive');const brain=makeBrainRecord('Brain 1');labSession.brains.push(brain);labSession.activeBrainId=brain.id;sessionRecordEvent('session-create','Created a new racing lab session.',{brainId:brain.id});await saveLabSessionNow();updateUI()}
async function loadStoredSession(id){if(!id)return;await saveLabSessionNow();const found=await dbRequest('readonly',s=>s.get(id));if(!found)throw new Error('Stored session was not found.');labSession=found;const brain=activeBrain()||labSession.brains?.[0];if(!brain)throw new Error('Stored session contains no brains.');labSession.activeBrainId=brain.id;localStorage.setItem(LAST_SESSION_KEY,labSession.id);applyBrainRecord(brain);sessionStorageStatus='Loaded from browser storage.';await refreshStoredSessionSummaries();updateUI()}
async function initializeSessionStorage(){
  try{await openSessionDb();const lastId=localStorage.getItem(LAST_SESSION_KEY),found=lastId?await dbRequest('readonly',s=>s.get(lastId)):null;if(found?.brains?.length){labSession=found;const brain=activeBrain()||labSession.brains[0];labSession.activeBrainId=brain.id;applyBrainRecord(brain);sessionStorageStatus='Restored local session.'}else await createNewLabSession(brainConfigSnapshot());await refreshStoredSessionSummaries();return labSession}catch(error){console.warn('IndexedDB unavailable; continuing with an in-memory session.',error);labSession=newSessionObject('Temporary Session');const brain=makeBrainRecord('Brain 1');labSession.brains.push(brain);labSession.activeBrainId=brain.id;sessionStorageStatus='Browser storage unavailable · session is temporary';return labSession}
}

function jsonSafe(value){if(ArrayBuffer.isView(value))return Array.from(value);if(Array.isArray(value))return value.map(jsonSafe);if(value&&typeof value==='object'){const out={};for(const[k,v]of Object.entries(value))out[k]=jsonSafe(v);return out}return value}
function downloadJson(value,filename){const blob=new Blob([JSON.stringify(jsonSafe(value),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportActiveBrain(){const brain=syncActiveBrainFromRuntime(true);if(!brain)return;downloadJson({format:'pov-rl-racing-lab-brain',version:1,exportedAt:nowIso(),brain},`${brain.name.replace(/[^a-z0-9-_]+/gi,'-').toLowerCase()}-update-${sim.update}.json`);scheduleSessionSave(100)}
function exportAllSession(){if(!labSession)return;syncActiveBrainFromRuntime(true);downloadJson({...labSession,format:'pov-rl-racing-lab-session',version:1,exportedAt:nowIso()},`${labSession.name.replace(/[^a-z0-9-_]+/gi,'-').toLowerCase()}-all.json`);scheduleSessionSave(100)}
function legacyJointNetwork(data){const a=data.architecture||{},n=data.net||{};if((data.version!==1&&data.version!==3)||a.inputs!==642||a.hidden!==48||a.actions!==ACTIONS||n.w1?.length!==48*642||n.b1?.length!==48||n.wp?.length!==ACTIONS*48||n.bp?.length!==ACTIONS||n.wv?.length!==48)throw new Error('Legacy checkpoint architecture is not a supported baseline brain.');return{kind:'mlp',config:{visionId:'gray32',networkId:'baseline'},layers:[{inputSize:642,outputSize:48,w:Array.from(n.w1),b:Array.from(n.b1)}],policy:{w:Array.from(n.wp),b:Array.from(n.bp)},value:{w:Array.from(n.wv),b:Number(n.bv)||0}}}
function legacyV2Network(data){const a=data.architecture||{},n=data.net||{},oldInputs=1282;if(data.version!==2||a.inputs!==oldInputs||a.hidden!==48||a.steerActions!==STEERS.length||a.throttleActions!==LONGITUDINAL.length)throw new Error('This v2 checkpoint cannot be migrated.');const layer=createDenseLayer(642,48);layer.w.fill(0);for(let j=0;j<48;j++){const oldBase=j*oldInputs,newBase=j*642;for(let i=0;i<640;i++)layer.w[newBase+i]=n.w1[oldBase+i];layer.w[newBase+640]=n.w1[oldBase+1280];layer.w[newBase+641]=n.w1[oldBase+1281]}layer.b.set(n.b1);const policy={w:new Float32Array(ACTIONS*48),b:new Float32Array(ACTIONS)};for(let t=0;t<LONGITUDINAL.length;t++)for(let st=0;st<STEERS.length;st++){const action=t*STEERS.length+st;policy.b[action]=(n.bs?.[st]||0)+(n.bt?.[t]||0);for(let j=0;j<48;j++)policy.w[action*48+j]=(n.ws?.[st*48+j]||0)+(n.wt?.[t*48+j]||0)}return{kind:'mlp',config:{visionId:'gray32',networkId:'baseline'},layers:[layer],policy,value:{w:Float32Array.from(n.wv||[]),b:Number(n.bv)||0}}}
function brainFromLegacyCheckpoint(data){const network=data.version===2?legacyV2Network(data):legacyJointNetwork(data),t=data.training||{};return{id:uid('brain'),name:`Imported v${data.version} brain`,createdAt:nowIso(),updatedAt:nowIso(),parentId:null,config:{visionId:'gray32',networkId:'baseline'},net:network,training:{update:Number(t.update)||0,totalExperience:Number(t.totalExperience)||0,temperature:clamp(Number(t.temperature)||1,.72,1.35),trackMode:t.trackMode in TRACK_DEFS?t.trackMode:'mixed',resetMode:['adaptive','1','2','4','8','never'].includes(String(t.resetMode))?String(t.resetMode):'adaptive',adaptiveResetInterval:[1,2,4,8].includes(Number(t.adaptiveResetInterval))?Number(t.adaptiveResetInterval):1,history:Array.isArray(t.history)?t.history:[],trainingWallSeconds:Number(t.trainingWallSeconds)||0,trainingSimSeconds:Number(t.trainingSimSeconds)||0,bestRunDistance:Number(t.bestRunDistance)||0},trainingSegments:[],races:[]}}
function normalizeImportedBrain(data){let raw;if(data?.format==='pov-rl-racing-lab-brain')raw=data.brain;else if(data?.format==='pov-rl-racing-lab-checkpoint')return brainFromLegacyCheckpoint(data);else throw new Error('Not a POV RL Racing Lab brain export.');if(!raw?.net)throw new Error('Brain export is incomplete.');const checked=networkFromSnapshot(raw.net),config=normalizedBrainConfig(raw.config||checked.config);return{...raw,id:uid('brain'),name:`${raw.name||'Imported brain'} import`,createdAt:nowIso(),updatedAt:nowIso(),config,net:networkSnapshot(checked),training:raw.training||{},trainingSegments:Array.isArray(raw.trainingSegments)?raw.trainingSegments:[],races:Array.isArray(raw.races)?raw.races:[]}}
async function importBrainData(data){if(!labSession)await createNewLabSession();syncActiveBrainFromRuntime(true);const brain=normalizeImportedBrain(data);labSession.brains.push(brain);labSession.activeBrainId=brain.id;applyBrainRecord(brain);sessionRecordEvent('brain-import',`Imported ${brain.name}.`,{brainId:brain.id});await saveLabSessionNow()}
async function importSessionData(data){if(data?.format!=='pov-rl-racing-lab-session'||!Array.isArray(data.brains)||!data.brains.length)throw new Error('Not a complete POV RL Racing Lab session export.');if(labSession)await saveLabSessionNow();const imported=structuredClone(data);imported.id=uid('session');imported.name=`${data.name||'Imported session'} import`;imported.createdAt=imported.updatedAt=nowIso();for(const brain of imported.brains){brain.id=uid('brain');brain.net=networkSnapshot(networkFromSnapshot(brain.net));brain.config=normalizedBrainConfig(brain.config);brain.updatedAt=nowIso()}imported.activeBrainId=imported.brains[0].id;imported.events=Array.isArray(imported.events)?imported.events.slice(-300):[];labSession=imported;applyBrainRecord(activeBrain());sessionRecordEvent('session-import','Imported a complete lab session.',{});await saveLabSessionNow()}
