// Browser-local lab sessions: normalized IndexedDB persistence, migration, management, and portable exports.
const SESSION_DB='pov-rl-racing-lab',SESSION_STORE='sessions',BRAIN_STORE='brains',SESSION_DB_VERSION=2,LAST_SESSION_KEY='pov-rl-racing-lab:last-session';
let sessionDb=null,labSession=null,storedSessionSummaries=[],sessionSaveTimer=null,sessionStorageStatus='Starting local storage…',storageEstimateAt=0;
let browserStorageInfo={supported:!!navigator.storage,usage:null,quota:null,persisted:null};
function nowIso(){return new Date().toISOString()}
function activeBrain(){return labSession?.brains?.find(b=>b.id===labSession.activeBrainId)||null}
function brainExperimentSeed(brain){return normalizeExperimentSeed(brain?.experiment?.seed??brain?.training?.seed??DEFAULT_EXPERIMENT_SEED)}
function ensureBrainExperimentMetadata(brain){if(!brain)return false;let changed=false;if(!brain.experiment||typeof brain.experiment!=='object'){brain.experiment={};changed=true}if(!Number.isFinite(Number(brain.experiment.seed))){brain.experiment.seed=randomExperimentSeed();changed=true}brain.experiment.seed=normalizeExperimentSeed(brain.experiment.seed);if(typeof brain.experiment.seededFromStart!=='boolean'){brain.experiment.seededFromStart=false;changed=true}if(!Number.isFinite(Number(brain.experiment.trackLayoutVersion))){brain.experiment.trackLayoutVersion=1;changed=true}else brain.experiment.trackLayoutVersion=Math.max(1,Math.trunc(Number(brain.experiment.trackLayoutVersion)));if(!brain.training||typeof brain.training!=='object'){brain.training={};changed=true}if(!Number.isFinite(Number(brain.training.seed))){brain.training.seed=brain.experiment.seed;changed=true}brain.training.seed=normalizeExperimentSeed(brain.training.seed,brain.experiment.seed);if(!brain.training.rngState||typeof brain.training.rngState!=='object'){brain.training.rngState=makeExperimentRngState(brain.training.seed);changed=true}else brain.training.rngState=normalizeExperimentRngState(brain.training.rngState,brain.training.seed);return changed}
function trainingStateSnapshot(){return{seed:sim.experimentSeed,rngState:{...sim.rngState},update:sim.update,totalExperience:sim.totalExperience,temperature:sim.temperature,trackMode:sim.trackMode,resetMode:sim.resetMode,adaptiveResetInterval:sim.adaptiveResetInterval,ppo:ppoSettingsSnapshot(),history:structuredClone(sim.history),trainingWallSeconds:sim.trainingWallSeconds,trainingSimSeconds:sim.trainingSimSeconds,bestRunDistance:sim.bestRunDistance,lastPpoMs:sim.lastPpoMs,ppoTotalMs:sim.ppoTotalMs,ppoCount:sim.ppoCount}}
function restoreTrainingState(t={},fallbackSeed=DEFAULT_EXPERIMENT_SEED){sim.pauseAfterLearning=false;resetExperimentRng(t.seed??fallbackSeed,t.rngState);applyPpoSettings(t.ppo||PPO_DEFAULTS);sim.update=Number(t.update)||0;sim.totalExperience=Number(t.totalExperience)||0;sim.temperature=clamp(Number(t.temperature)||1.35,.72,1.35);sim.trackMode=t.trackMode in TRACK_DEFS?t.trackMode:'mixed';sim.resetMode=['adaptive','1','2','4','8','never'].includes(String(t.resetMode))?String(t.resetMode):'adaptive';sim.adaptiveResetInterval=[1,2,4,8].includes(Number(t.adaptiveResetInterval))?Number(t.adaptiveResetInterval):1;sim.history=Array.isArray(t.history)?structuredClone(t.history):[];sim.lastMetrics=sim.history.at(-1)||null;sim.trainingWallSeconds=Number(t.trainingWallSeconds)||0;sim.trainingSimSeconds=Number(t.trainingSimSeconds)||0;sim.bestRunDistance=Number(t.bestRunDistance)||Math.max(0,...sim.history.map(x=>Number(x.bestRunDistance)||Number(x.batchBestRunDistance)||0));sim.lastPpoMs=Number(t.lastPpoMs)||Number(sim.lastMetrics?.ppoMs)||0;sim.ppoTotalMs=Number(t.ppoTotalMs)||0;sim.ppoCount=Number(t.ppoCount)||0;if(!sim.ppoCount&&sim.history.length){const timed=sim.history.filter(x=>Number(x.ppoMs)>0);sim.ppoCount=timed.length;sim.ppoTotalMs=timed.reduce((s,x)=>s+Number(x.ppoMs||0),0)}sim.experience=0;sim.lastLoss=Number(sim.lastMetrics?.loss)||0;sim.updatesSinceGridReset=0;sim.physicsAcc=0;sim.decisionAcc=0}
function resetTrainingState(seed=randomExperimentSeed()){sim.pauseAfterLearning=false;resetExperimentRng(seed);applyPpoSettings(PPO_DEFAULTS);sim.update=0;sim.experience=0;sim.totalExperience=0;sim.temperature=1.35;sim.lastLoss=0;sim.history=[];sim.lastMetrics=null;sim.trainingWallSeconds=0;sim.trainingSimSeconds=0;sim.bestRunDistance=0;sim.lastPpoMs=0;sim.ppoTotalMs=0;sim.ppoCount=0;sim.adaptiveResetInterval=1;sim.updatesSinceGridReset=0;sim.physicsAcc=0;sim.decisionAcc=0;resetBatchTelemetry();resetRecentTelemetry()}
function resetDriversForBrain(){drivers.forEach(c=>{c.rollout=[];c.lastObs=null;c.lastForward=null;c.totalReward=0;c.totalProgress=0;c.lap=0;c.collisions=0;c.overtakes=0;c.latestRGBA=null;c.mesh.visible=true});resetGrid();primeObservations();drivers.forEach(chooseAction)}
function makeBrainRecord(name=`Brain ${(labSession?.brains?.length||0)+1}`,parentId=null){return{id:uid('brain'),name,createdAt:nowIso(),updatedAt:nowIso(),parentId,experiment:{seed:sim.experimentSeed,seededFromStart:true,trackLayoutVersion:TRACK_LAYOUT_VERSION},config:brainConfigSnapshot(),net:networkSnapshot(),training:trainingStateSnapshot(),trainingSegments:[],races:[]}}
function syncActiveBrainFromRuntime(includeNet=true){const brain=activeBrain();if(!brain)return null;brain.config=brainConfigSnapshot();brain.experiment={...(brain.experiment||{}),seed:sim.experimentSeed,seededFromStart:brain.experiment?.seededFromStart!==false};if(includeNet)brain.net=networkSnapshot();brain.training=trainingStateSnapshot();brain.updatedAt=nowIso();return brain}
function sessionRecordEvent(type,text,data={}){if(!labSession)return;labSession.events.push({id:uid('event'),at:nowIso(),type,text,data:structuredClone(data)});if(labSession.events.length>300)labSession.events.splice(0,labSession.events.length-300);labSession.updatedAt=nowIso();scheduleSessionSave()}
function sessionAfterLearningUpdate(metrics){const brain=activeBrain();if(!brain)return;brain.training=trainingStateSnapshot();brain.updatedAt=nowIso();const segments=brain.trainingSegments||(brain.trainingSegments=[]),last=segments.at(-1),layoutVersion=Number(metrics.trackLayoutVersion)||TRACK_LAYOUT_VERSION;if(last&&last.trackId===sim.trackMode&&(Number(last.trackLayoutVersion)||1)===layoutVersion&&last.endUpdate===sim.update-1){last.endUpdate=sim.update;last.endExperience=sim.totalExperience;last.bestRunDistance=Math.max(last.bestRunDistance||0,metrics.batchBestRunDistance||0);last.laps=(last.laps||0)+(metrics.laps||0)}else segments.push({trackId:sim.trackMode,trackLayoutVersion:layoutVersion,startUpdate:sim.update,endUpdate:sim.update,startExperience:Math.max(0,sim.totalExperience-sim.ppoBatchTarget),endExperience:sim.totalExperience,bestRunDistance:metrics.batchBestRunDistance||0,laps:metrics.laps||0});labSession.updatedAt=nowIso();scheduleSessionSave()}
function sessionRecordRace(trackId,laps,results){const brain=activeBrain();if(!brain)return;const record={at:nowIso(),trackId,trackLayoutVersion:TRACK_LAYOUT_VERSION,laps,policyUpdate:sim.update,results:structuredClone(results)};brain.races.push(record);if(brain.races.length>80)brain.races.shift();sessionRecordEvent('race',`Race completed: ${TRACK_DEFS[trackId]?.name||trackId}, ${laps} lap${laps===1?'':'s'} · layout v${TRACK_LAYOUT_VERSION}.`,{brainId:brain.id,...record})}
function sessionRecordTrackChange(trackId){const brain=activeBrain();sessionRecordEvent('track',`Training track set to ${TRACK_DEFS[trackId]?.name||trackId} · layout v${TRACK_LAYOUT_VERSION}.`,{brainId:brain?.id||null,trackId,trackLayoutVersion:TRACK_LAYOUT_VERSION,update:sim.update})}

function sessionMetadata(session=labSession){if(!session)return null;const{brains,...meta}=session;return{...structuredClone(meta),storageVersion:2,brainCount:brains?.length||0}}
function brainStorageRecord(brain,sessionId=labSession?.id,order=labSession?.brains?.indexOf(brain)??0){return{...structuredClone(brain),sessionId,order:Math.max(0,order)}}
function brainRuntimeRecord(row){if(!row)return null;const{sessionId,order,...brain}=row;return brain}
function openSessionDb(){if(sessionDb)return Promise.resolve(sessionDb);return new Promise((resolve,reject)=>{const req=indexedDB.open(SESSION_DB,SESSION_DB_VERSION);req.onupgradeneeded=event=>{const db=req.result,tx=req.transaction;const sessions=db.objectStoreNames.contains(SESSION_STORE)?tx.objectStore(SESSION_STORE):db.createObjectStore(SESSION_STORE,{keyPath:'id'});let brains;if(db.objectStoreNames.contains(BRAIN_STORE)){brains=tx.objectStore(BRAIN_STORE);if(!brains.indexNames.contains('sessionId'))brains.createIndex('sessionId','sessionId',{unique:false})}else{brains=db.createObjectStore(BRAIN_STORE,{keyPath:'id'});brains.createIndex('sessionId','sessionId',{unique:false})}if(event.oldVersion<2){const cursorReq=sessions.openCursor();cursorReq.onsuccess=()=>{const cursor=cursorReq.result;if(!cursor)return;const row=cursor.value;if(Array.isArray(row.brains)){row.brains.forEach((brain,order)=>brains.put(brainStorageRecord(brain,row.id,order)));const{brains:embedded,...meta}=row;cursor.update({...meta,storageVersion:2,brainCount:embedded.length})}cursor.continue()}}};req.onsuccess=()=>{sessionDb=req.result;resolve(sessionDb)};req.onerror=()=>reject(req.error||new Error('Could not open IndexedDB.'))})}
function dbRequest(storeName,mode,work){return openSessionDb().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction(storeName,mode),store=tx.objectStore(storeName);let req,result;try{req=work(store,tx)}catch(error){try{tx.abort()}catch{}reject(error);return}if(req){req.onsuccess=()=>{result=req.result};req.onerror=()=>reject(req.error)}tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('IndexedDB transaction aborted.'))}))}
function dbTransaction(storeNames,mode,work){return openSessionDb().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction(storeNames,mode);try{work(tx)}catch(error){try{tx.abort()}catch{}reject(error);return}tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('IndexedDB transaction aborted.'))}))}
async function loadBrainRows(sessionId){const rows=await dbRequest(BRAIN_STORE,'readonly',s=>s.index('sessionId').getAll(sessionId));return(rows||[]).sort((a,b)=>(a.order??0)-(b.order??0))}
async function loadSessionRecord(id){const meta=await dbRequest(SESSION_STORE,'readonly',s=>s.get(id));if(!meta)return null;const rows=await loadBrainRows(id),brains=rows.map(brainRuntimeRecord),changed=[];brains.forEach((brain,order)=>{if(ensureBrainExperimentMetadata(brain))changed.push({brain,order})});if(changed.length)await dbTransaction([BRAIN_STORE],'readwrite',tx=>{const store=tx.objectStore(BRAIN_STORE);for(const item of changed)store.put(brainStorageRecord(item.brain,id,item.order))});return{...meta,brains}}
async function persistWholeSession(session=labSession){if(!session)return;await dbTransaction([SESSION_STORE,BRAIN_STORE],'readwrite',tx=>{tx.objectStore(SESSION_STORE).put(sessionMetadata(session));const store=tx.objectStore(BRAIN_STORE);session.brains.forEach((brain,order)=>store.put(brainStorageRecord(brain,session.id,order)))})}
async function persistSessionAndBrain(session=labSession,brain=activeBrain()){if(!session)return;await dbTransaction([SESSION_STORE,BRAIN_STORE],'readwrite',tx=>{tx.objectStore(SESSION_STORE).put(sessionMetadata(session));if(brain)tx.objectStore(BRAIN_STORE).put(brainStorageRecord(brain,session.id,session.brains.indexOf(brain)))})}
async function deleteStoredSession(id){await dbTransaction([SESSION_STORE,BRAIN_STORE],'readwrite',tx=>{tx.objectStore(SESSION_STORE).delete(id);const brains=tx.objectStore(BRAIN_STORE),req=brains.index('sessionId').openKeyCursor(IDBKeyRange.only(id));req.onsuccess=()=>{const cursor=req.result;if(!cursor)return;brains.delete(cursor.primaryKey);cursor.continue()}})}
async function clearStoredLabData(){await dbTransaction([SESSION_STORE,BRAIN_STORE],'readwrite',tx=>{tx.objectStore(SESSION_STORE).clear();tx.objectStore(BRAIN_STORE).clear()})}
async function refreshStoredSessionSummaries(){try{const rows=await dbRequest(SESSION_STORE,'readonly',s=>s.getAll());storedSessionSummaries=rows.map(x=>({id:x.id,name:x.name,updatedAt:x.updatedAt,brainCount:Number(x.brainCount)||0})).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))}catch{storedSessionSummaries=[]}return storedSessionSummaries}
async function refreshBrowserStorageInfo(force=false){const now=Date.now();if(!force&&now-storageEstimateAt<5000)return browserStorageInfo;storageEstimateAt=now;try{const estimate=await navigator.storage?.estimate?.(),persisted=await navigator.storage?.persisted?.();browserStorageInfo={supported:!!navigator.storage,usage:Number.isFinite(estimate?.usage)?estimate.usage:null,quota:Number.isFinite(estimate?.quota)?estimate.quota:null,persisted:typeof persisted==='boolean'?persisted:null}}catch{browserStorageInfo={supported:false,usage:null,quota:null,persisted:null}}if(typeof updateSessionUI==='function')updateSessionUI();return browserStorageInfo}
async function requestPersistentStorage(){if(!navigator.storage?.persist){sessionStorageStatus='Persistent-storage requests are not supported by this browser.';updateSessionUI();return false}const granted=await navigator.storage.persist();sessionStorageStatus=granted?'Persistent browser storage granted.':'Browser kept this origin on best-effort storage.';await refreshBrowserStorageInfo(true);return granted}
async function saveLabSessionNow(){if(!labSession)return;try{syncActiveBrainFromRuntime(true);labSession.updatedAt=nowIso();sessionStorageStatus='Saving locally…';if(typeof updateSessionUI==='function')updateSessionUI();await persistSessionAndBrain();localStorage.setItem(LAST_SESSION_KEY,labSession.id);sessionStorageStatus=`Saved locally · ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}`;await refreshStoredSessionSummaries();refreshBrowserStorageInfo();if(typeof updateSessionUI==='function')updateSessionUI()}catch(error){sessionStorageStatus=`Local save failed: ${error.message}`;if(typeof updateSessionUI==='function')updateSessionUI();console.warn('Session autosave failed.',error)}}
function scheduleSessionSave(delay=800){clearTimeout(sessionSaveTimer);sessionStorageStatus='Local changes pending…';sessionSaveTimer=setTimeout(()=>{const run=()=>saveLabSessionNow();if('requestIdleCallback'in globalThis)requestIdleCallback(run,{timeout:1800});else run()},delay);if(typeof updateSessionUI==='function')updateSessionUI()}

function sameBrainConfig(a,b){const x=normalizedBrainConfig(a),y=normalizedBrainConfig(b);return x.visionId===y.visionId&&x.networkId===y.networkId}
function applyBrainRecord(brain){ensureBrainExperimentMetadata(brain);const recordConfig=normalizedBrainConfig(brain.config),networkConfig=normalizedBrainConfig(brain.net?.config);if(!sameBrainConfig(recordConfig,networkConfig))throw new Error('Brain record configuration does not match its saved network configuration.');brain.config=recordConfig;sim.running=false;sim.learning=false;sim.mode='learn';sim.headless=false;sim.raceFinished=false;applyBrainConfiguration(recordConfig);rebuildPerceptionResources();net=networkFromSnapshot(brain.net);if(net.layers[0]?.inputSize!==INPUTS)throw new Error('Brain network input size does not match its configured observation.');restoreTrainingState(brain.training,brainExperimentSeed(brain));resetBatchTelemetry();resetRecentTelemetry();buildTrack(sim.trackMode);resetDriversForBrain();if($('trackSelect'))$('trackSelect').value=sim.trackMode;if($('resetMode'))$('resetMode').value=sim.resetMode;if($('visionSelect'))$('visionSelect').value=brain.config.visionId;if($('networkSelect'))$('networkSelect').value=brain.config.networkId;if(typeof syncPpoControls==='function')syncPpoControls();if($('raceResult'))$('raceResult').textContent=`Loaded ${brain.name}. Learning is paused on ${TRACK_DEFS[sim.trackMode].name}.`;if(typeof refreshBrainSetupSummary==='function')refreshBrainSetupSummary();if(typeof updateUI==='function')updateUI()}
async function switchActiveBrain(id){if(sim.learning)throw new Error('Wait for the current PPO update to finish before switching brains.');if(!labSession||id===labSession.activeBrainId)return;await saveLabSessionNow();const next=labSession.brains.find(b=>b.id===id);if(!next)return;labSession.activeBrainId=id;applyBrainRecord(next);sessionRecordEvent('brain-switch',`Switched to ${next.name}.`,{brainId:id});await saveLabSessionNow()}
function setupFreshBrainRuntime(config,trackId=sim.trackMode,resetMode=sim.resetMode,seed=randomExperimentSeed()){sim.running=false;sim.mode='learn';sim.headless=false;sim.raceFinished=false;applyBrainConfiguration(config);rebuildPerceptionResources();resetTrainingState(seed);net=createNetwork();sim.trackMode=trackId in TRACK_DEFS?trackId:'mixed';sim.resetMode=['adaptive','1','2','4','8','never'].includes(String(resetMode))?String(resetMode):'adaptive';buildTrack(sim.trackMode);resetDriversForBrain();if($('trackSelect'))$('trackSelect').value=sim.trackMode;if($('resetMode'))$('resetMode').value=sim.resetMode}
async function createFreshBrain(config,name=null,seed=randomExperimentSeed()){if(sim.learning)throw new Error('Wait for the current PPO update to finish before creating a brain.');if(!labSession)return;await saveLabSessionNow();const c=normalizedBrainConfig(config),track=sim.trackMode,reset=sim.resetMode,experimentSeed=normalizeExperimentSeed(seed,randomExperimentSeed());setupFreshBrainRuntime(c,track,reset,experimentSeed);const brain=makeBrainRecord(name||`Brain ${labSession.brains.length+1}`);labSession.brains.push(brain);labSession.activeBrainId=brain.id;sessionRecordEvent('brain-create',`Created ${brain.name}: ${brainConfigLabel(c)} · seed ${experimentSeed}.`,{brainId:brain.id,config:c,seed:experimentSeed});await saveLabSessionNow();updateUI()}
async function duplicateActiveBrain(){if(sim.learning)throw new Error('Wait for the current PPO update to finish before duplicating a brain.');await saveLabSessionNow();const source=activeBrain();if(!source||!labSession)return;const clone=structuredClone(source);clone.id=uid('brain');clone.name=`${source.name} copy`;clone.parentId=source.id;clone.createdAt=clone.updatedAt=nowIso();labSession.brains.push(clone);labSession.activeBrainId=clone.id;applyBrainRecord(clone);sessionRecordEvent('brain-duplicate',`Duplicated ${source.name} as ${clone.name}.`,{brainId:clone.id,parentId:source.id});await saveLabSessionNow()}
async function renameActiveBrain(name){const brain=activeBrain();name=String(name||'').trim();if(!brain||!name)return;brain.name=name;brain.updatedAt=nowIso();sessionRecordEvent('brain-rename',`Active brain renamed to ${name}.`,{brainId:brain.id});await saveLabSessionNow()}
async function renameLabSession(name){name=String(name||'').trim();if(!labSession||!name)return;labSession.name=name;labSession.updatedAt=nowIso();await saveLabSessionNow()}
function newSessionObject(name='Racing Lab Session'){return{format:'pov-rl-racing-lab-session',version:1,id:uid('session'),name,createdAt:nowIso(),updatedAt:nowIso(),activeBrainId:null,brains:[],events:[]}}
async function createNewLabSession(config=brainConfigSnapshot()){if(sim.learning)throw new Error('Wait for the current PPO update to finish before changing sessions.');if(labSession)await saveLabSessionNow();labSession=newSessionObject(`Session ${new Date().toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}`);setupFreshBrainRuntime(config,'mixed','adaptive');const brain=makeBrainRecord('Brain 1');labSession.brains.push(brain);labSession.activeBrainId=brain.id;sessionRecordEvent('session-create','Created a new racing lab session.',{brainId:brain.id});await persistWholeSession();localStorage.setItem(LAST_SESSION_KEY,labSession.id);sessionStorageStatus='New session saved locally.';await refreshStoredSessionSummaries();refreshBrowserStorageInfo(true);updateUI()}
async function loadStoredSession(id){if(sim.learning)throw new Error('Wait for the current PPO update to finish before changing sessions.');if(!id)return;await saveLabSessionNow();const found=await loadSessionRecord(id);if(!found)throw new Error('Stored session was not found.');const brain=found.brains?.find(b=>b.id===found.activeBrainId)||found.brains?.[0];if(!brain)throw new Error('Stored session contains no brains.');labSession=found;labSession.activeBrainId=brain.id;localStorage.setItem(LAST_SESSION_KEY,labSession.id);applyBrainRecord(brain);sessionStorageStatus='Loaded from browser storage.';await refreshStoredSessionSummaries();refreshBrowserStorageInfo(true);updateUI()}
async function deleteBrain(id){if(sim.learning)throw new Error('Wait for the current PPO update to finish before deleting a brain.');const brain=labSession?.brains?.find(b=>b.id===id);if(!brain)return;if(labSession.brains.length<=1){log('A session must keep at least one brain. Delete the session or clear local data instead.');return}if(!confirm(`Delete ${brain.name}? Its learned weights and history will be removed from this browser session. Export it first if you may want it later.`))return;await saveLabSessionNow();const index=labSession.brains.findIndex(b=>b.id===id),wasActive=labSession.activeBrainId===id;labSession.brains.splice(index,1);await dbRequest(BRAIN_STORE,'readwrite',s=>s.delete(id));if(wasActive){const next=labSession.brains[Math.min(index,labSession.brains.length-1)];labSession.activeBrainId=next.id;applyBrainRecord(next)}sessionRecordEvent('brain-delete',`Deleted ${brain.name}.`,{brainId:id});syncActiveBrainFromRuntime(true);labSession.updatedAt=nowIso();await persistWholeSession();localStorage.setItem(LAST_SESSION_KEY,labSession.id);sessionStorageStatus='Brain deleted and remaining library saved.';await refreshStoredSessionSummaries();refreshBrowserStorageInfo(true);updateUI()}
async function deleteCurrentSession(){if(sim.learning)throw new Error('Wait for the current PPO update to finish before deleting a session.');if(!labSession)return;if(!confirm(`Delete session “${labSession.name}” and all ${labSession.brains.length} of its locally stored brain${labSession.brains.length===1?'':'s'}? Export All first if you may want this experiment later.`))return;sim.running=false;clearTimeout(sessionSaveTimer);const deletedId=labSession.id,config=brainConfigSnapshot();await deleteStoredSession(deletedId);labSession=null;if(localStorage.getItem(LAST_SESSION_KEY)===deletedId)localStorage.removeItem(LAST_SESSION_KEY);await refreshStoredSessionSummaries();if(storedSessionSummaries.length)await loadStoredSession(storedSessionSummaries[0].id);else await createNewLabSession(config);sessionStorageStatus='Session deleted; another session is active.';refreshBrowserStorageInfo(true);updateUI()}
async function clearAllLocalLabData(){if(sim.learning)throw new Error('Wait for the current PPO update to finish before clearing storage.');if(!confirm('Clear ALL locally stored POV RL Racing Lab sessions and brains in this browser? This cannot be undone. Export All first if you need a backup.'))return;sim.running=false;clearTimeout(sessionSaveTimer);const config=brainConfigSnapshot();await clearStoredLabData();localStorage.removeItem(LAST_SESSION_KEY);labSession=null;storedSessionSummaries=[];await createNewLabSession(config);sessionStorageStatus='All previous local lab data cleared; a fresh session was created.';refreshBrowserStorageInfo(true);updateUI()}
async function initializeSessionStorage(){try{await openSessionDb();const lastId=localStorage.getItem(LAST_SESSION_KEY),found=lastId?await loadSessionRecord(lastId):null;if(found?.brains?.length){labSession=found;const brain=activeBrain()||labSession.brains[0];labSession.activeBrainId=brain.id;applyBrainRecord(brain);sessionStorageStatus='Restored local session.'}else await createNewLabSession(brainConfigSnapshot());await refreshStoredSessionSummaries();await refreshBrowserStorageInfo(true);return labSession}catch(error){console.warn('IndexedDB unavailable; continuing with an in-memory session.',error);labSession=newSessionObject('Temporary Session');const brain=makeBrainRecord('Brain 1');labSession.brains.push(brain);labSession.activeBrainId=brain.id;sessionStorageStatus='Browser storage unavailable · session is temporary';return labSession}}

function jsonSafe(value){if(ArrayBuffer.isView(value))return Array.from(value);if(Array.isArray(value))return value.map(jsonSafe);if(value&&typeof value==='object'){const out={};for(const[k,v]of Object.entries(value))out[k]=jsonSafe(v);return out}return value}
function portableBrain(brain){const{sessionId,order,...clean}=brain||{};return structuredClone(clean)}
function portableSession(session=labSession){if(!session)return null;const{storageVersion,brainCount,...base}=session;return{...structuredClone(base),format:'pov-rl-racing-lab-session',version:1,brains:session.brains.map(portableBrain)}}
function downloadJson(value,filename){const blob=new Blob([JSON.stringify(jsonSafe(value),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportBrainRecord(brain){if(sim.learning){log('Wait for the current PPO update to finish before exporting a brain.');return}if(!brain)return;if(brain.id===labSession?.activeBrainId)syncActiveBrainFromRuntime(true);const clean=portableBrain(brain);downloadJson({format:'pov-rl-racing-lab-brain',version:1,exportedAt:nowIso(),brain:clean},`${clean.name.replace(/[^a-z0-9-_]+/gi,'-').toLowerCase()}-update-${clean.training?.update||0}.json`);scheduleSessionSave(100)}
function exportBrainById(id){exportBrainRecord(labSession?.brains?.find(b=>b.id===id))}
function exportActiveBrain(){exportBrainRecord(activeBrain())}
function exportAllSession(){if(sim.learning){log('Wait for the current PPO update to finish before exporting the session.');return}if(!labSession)return;syncActiveBrainFromRuntime(true);const exported=portableSession();downloadJson({...exported,exportedAt:nowIso()},`${labSession.name.replace(/[^a-z0-9-_]+/gi,'-').toLowerCase()}-all.json`);scheduleSessionSave(100)}
function legacyJointNetwork(data){const a=data.architecture||{},n=data.net||{};if((data.version!==1&&data.version!==3)||a.inputs!==642||a.hidden!==48||a.actions!==ACTIONS||n.w1?.length!==48*642||n.b1?.length!==48||n.wp?.length!==ACTIONS*48||n.bp?.length!==ACTIONS||n.wv?.length!==48)throw new Error('Legacy checkpoint architecture is not a supported baseline brain.');return{kind:'mlp',config:{visionId:'gray32',networkId:'baseline'},layers:[{inputSize:642,outputSize:48,w:Array.from(n.w1),b:Array.from(n.b1)}],policy:{w:Array.from(n.wp),b:Array.from(n.bp)},value:{w:Array.from(n.wv),b:Number(n.bv)||0}}}
function legacyV2Network(data){const a=data.architecture||{},n=data.net||{},oldInputs=1282;if(data.version!==2||a.inputs!==oldInputs||a.hidden!==48||a.steerActions!==STEERS.length||a.throttleActions!==LONGITUDINAL.length)throw new Error('This v2 checkpoint cannot be migrated.');const layer=createDenseLayer(642,48);layer.w.fill(0);for(let j=0;j<48;j++){const oldBase=j*oldInputs,newBase=j*642;for(let i=0;i<640;i++)layer.w[newBase+i]=n.w1[oldBase+i];layer.w[newBase+640]=n.w1[oldBase+1280];layer.w[newBase+641]=n.w1[oldBase+1281]}layer.b.set(n.b1);const policy={w:new Float32Array(ACTIONS*48),b:new Float32Array(ACTIONS)};for(let t=0;t<LONGITUDINAL.length;t++)for(let st=0;st<STEERS.length;st++){const action=t*STEERS.length+st;policy.b[action]=(n.bs?.[st]||0)+(n.bt?.[t]||0);for(let j=0;j<48;j++)policy.w[action*48+j]=(n.ws?.[st*48+j]||0)+(n.wt?.[t*48+j]||0)}return{kind:'mlp',config:{visionId:'gray32',networkId:'baseline'},layers:[layer],policy,value:{w:Float32Array.from(n.wv||[]),b:Number(n.bv)||0}}}
function brainFromLegacyCheckpoint(data){const network=data.version===2?legacyV2Network(data):legacyJointNetwork(data),t=data.training||{},seed=randomExperimentSeed();return{id:uid('brain'),name:`Imported v${data.version} brain`,createdAt:nowIso(),updatedAt:nowIso(),parentId:null,experiment:{seed,seededFromStart:false,trackLayoutVersion:1},config:{visionId:'gray32',networkId:'baseline'},net:network,training:{seed,rngState:makeExperimentRngState(seed),update:Number(t.update)||0,totalExperience:Number(t.totalExperience)||0,temperature:clamp(Number(t.temperature)||1,.72,1.35),trackMode:t.trackMode in TRACK_DEFS?t.trackMode:'mixed',resetMode:['adaptive','1','2','4','8','never'].includes(String(t.resetMode))?String(t.resetMode):'adaptive',adaptiveResetInterval:[1,2,4,8].includes(Number(t.adaptiveResetInterval))?Number(t.adaptiveResetInterval):1,history:Array.isArray(t.history)?t.history:[],trainingWallSeconds:Number(t.trainingWallSeconds)||0,trainingSimSeconds:Number(t.trainingSimSeconds)||0,bestRunDistance:Number(t.bestRunDistance)||0,lastPpoMs:0,ppoTotalMs:0,ppoCount:0},trainingSegments:[],races:[]}}
function normalizeImportedBrain(data){let raw;if(data?.format==='pov-rl-racing-lab-brain')raw=data.brain;else if(data?.format==='pov-rl-racing-lab-checkpoint')return brainFromLegacyCheckpoint(data);else throw new Error('Not a POV RL Racing Lab brain export.');if(!raw?.net)throw new Error('Brain export is incomplete.');const checked=networkFromSnapshot(raw.net),config=normalizedBrainConfig(raw.config||checked.config);if(!sameBrainConfig(config,checked.config))throw new Error('Imported brain configuration does not match its network.');const brain={...portableBrain(raw),id:uid('brain'),name:`${raw.name||'Imported brain'} import`,createdAt:nowIso(),updatedAt:nowIso(),config,net:networkSnapshot(checked),training:raw.training||{},trainingSegments:Array.isArray(raw.trainingSegments)?raw.trainingSegments:[],races:Array.isArray(raw.races)?raw.races:[]};ensureBrainExperimentMetadata(brain);return brain}
async function importBrainData(data){if(sim.learning)throw new Error('Wait for the current PPO update to finish before importing a brain.');if(!labSession)await createNewLabSession();await saveLabSessionNow();const brain=normalizeImportedBrain(data);labSession.brains.push(brain);labSession.activeBrainId=brain.id;applyBrainRecord(brain);sessionRecordEvent('brain-import',`Imported ${brain.name}.`,{brainId:brain.id});await saveLabSessionNow()}
async function importSessionData(data){if(sim.learning)throw new Error('Wait for the current PPO update to finish before importing a session.');if(data?.format!=='pov-rl-racing-lab-session'||!Array.isArray(data.brains)||!data.brains.length)throw new Error('Not a complete POV RL Racing Lab session export.');if(labSession)await saveLabSessionNow();const imported=structuredClone(data),oldActive=data.activeBrainId,idMap=new Map();imported.id=uid('session');imported.name=`${data.name||'Imported session'} import`;imported.createdAt=imported.updatedAt=nowIso();for(const brain of imported.brains){const oldId=brain.id,newId=uid('brain');idMap.set(oldId,newId);brain.id=newId;brain.net=networkSnapshot(networkFromSnapshot(brain.net));brain.config=normalizedBrainConfig(brain.config);if(!sameBrainConfig(brain.config,brain.net.config))throw new Error(`Imported brain ${brain.name||oldId} has mismatched configuration.`);ensureBrainExperimentMetadata(brain);brain.updatedAt=nowIso()}for(const brain of imported.brains)if(brain.parentId)brain.parentId=idMap.get(brain.parentId)||null;imported.activeBrainId=idMap.get(oldActive)||imported.brains[0].id;imported.events=Array.isArray(imported.events)?imported.events.slice(-300):[];delete imported.exportedAt;delete imported.storageVersion;delete imported.brainCount;labSession=imported;applyBrainRecord(activeBrain());labSession.events.push({id:uid('event'),at:nowIso(),type:'session-import',text:'Imported a complete lab session.',data:{}});await persistWholeSession();localStorage.setItem(LAST_SESSION_KEY,labSession.id);sessionStorageStatus='Imported complete session and saved it locally.';await refreshStoredSessionSummaries();refreshBrowserStorageInfo(true);updateUI()}
