// Clipped PPO backpropagation generalized across configurable dense tanh layers.
function buildTrainingBatch(){const batch=[];for(const car of drivers){let nextValue=car.lastValue,gae=0;for(let i=car.rollout.length-1;i>=0;i--){const e=car.rollout[i],mask=e.done?0:1,delta=e.reward+GAMMA*nextValue*mask-e.value;gae=delta+GAMMA*GAE_LAMBDA*mask*gae;e.adv=gae;e.ret=e.value+gae;nextValue=e.value}batch.push(...car.rollout)}let mean=0;for(const e of batch)mean+=e.adv;mean/=Math.max(1,batch.length);let variance=0;for(const e of batch){const d=e.adv-mean;variance+=d*d}variance/=Math.max(1,batch.length);const sd=Math.sqrt(variance)+1e-6;for(const e of batch)e.adv=(e.adv-mean)/sd;return batch}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=(experimentRandom('shuffle')*(i+1))|0;[a[i],a[j]]=[a[j],a[i]]}}
function trainSample(e,lr){
  const out=forward(e.obs),last=out.hidden.at(-1),newLog=Math.log(Math.max(1e-7,out.probs[e.action])),ratio=Math.exp(clamp(newLog-e.logp,-10,10)),clipped=(e.adv>=0&&ratio>1+sim.ppoClip)||(e.adv<0&&ratio<1-sim.ppoClip),dLogP=clipped?0:-e.adv*ratio,dLogits=new Float32Array(ACTIONS);
  for(let a=0;a<ACTIONS;a++)dLogits[a]=clamp(dLogP*((a===e.action?1:0)-out.probs[a]),-3,3);const dValue=clamp(.35*(out.value-e.ret),-3,3);
  let grad=new Float32Array(last.length);for(let j=0;j<last.length;j++){let g=net.value.w[j]*dValue;for(let a=0;a<ACTIONS;a++)g+=net.policy.w[a*last.length+j]*dLogits[a];grad[j]=g}
  const deltas=new Array(net.layers.length);for(let l=net.layers.length-1;l>=0;l--){const layer=net.layers[l],act=out.hidden[l],dz=new Float32Array(layer.outputSize);for(let j=0;j<layer.outputSize;j++)dz[j]=clamp(grad[j]*(1-act[j]*act[j]),-3,3);deltas[l]=dz;if(l>0){const prev=new Float32Array(layer.inputSize);for(let j=0;j<layer.outputSize;j++){const g=dz[j],row=j*layer.inputSize;for(let i=0;i<layer.inputSize;i++)prev[i]+=layer.w[row+i]*g}grad=prev}}
  for(let a=0;a<ACTIONS;a++){const base=a*last.length,g=dLogits[a];for(let j=0;j<last.length;j++)net.policy.w[base+j]-=lr*g*last[j];net.policy.b[a]-=lr*g}for(let j=0;j<last.length;j++)net.value.w[j]-=lr*dValue*last[j];net.value.b-=lr*dValue;
  for(let l=0;l<net.layers.length;l++){const layer=net.layers[l],input=l===0?e.obs:out.hidden[l-1],dz=deltas[l];for(let j=0;j<layer.outputSize;j++){const row=j*layer.inputSize,g=dz[j];for(let i=0;i<layer.inputSize;i++)layer.w[row+i]-=lr*g*input[i];layer.b[j]-=lr*g}}
  const policyLoss=-Math.min(ratio*e.adv,clamp(ratio,1-sim.ppoClip,1+sim.ppoClip)*e.adv),valueLoss=.5*(out.value-e.ret)*(out.value-e.ret);return policyLoss+.35*valueLoss;
}
function captureBatchMetrics(avgReward){const liveDistances=drivers.map(c=>c.episodePeakProgress),distanceSum=sim.batchEpisodeDistance+liveDistances.reduce((a,b)=>a+b,0),distanceCount=sim.batchEpisodes+DRIVER_COUNT,avgRunDistance=distanceSum/Math.max(1,distanceCount),batchBestRunDistance=Math.max(sim.batchBestRunDistance,...liveDistances);sim.bestRunDistance=Math.max(sim.bestRunDistance,batchBestRunDistance);const metrics={update:sim.update,seed:sim.experimentSeed,trackId:sim.trackMode,rewardPerExp:avgReward,forwardPerExp:sim.batchForwardMeters/Math.max(1,sim.experience),offRoadPct:sim.batchOffRoadSeconds/Math.max(.001,sim.batchDriverSeconds)*100,avgRunDistance,batchBestRunDistance,bestRunDistance:sim.bestRunDistance,resets:sim.batchResets,laps:sim.batchLaps,collisions:sim.collisions,loss:sim.lastLoss,ppoMs:sim.lastPpoMs,avgPpoMs:sim.ppoCount?sim.ppoTotalMs/sim.ppoCount:0,ppo:ppoSettingsSnapshot(),totalExperience:sim.totalExperience,wallSeconds:sim.trainingWallSeconds,simSeconds:sim.trainingSimSeconds,steer:[...sim.batchSteerCounts],throttle:[...sim.batchThrottleCounts]};sim.lastMetrics=metrics;sim.history.push(metrics);return metrics}
function adaptiveResetCadence(metrics){const lapsWorth=metrics.avgRunDistance/Math.max(1,trackLength),before=sim.adaptiveResetInterval;let interval=before;if(interval===1&&(metrics.laps>=2||lapsWorth>=.45))interval=2;else if(interval===2&&(metrics.laps>=4||lapsWorth>=.90))interval=4;else if(interval===4&&(metrics.laps>=8||lapsWorth>=1.80))interval=8;sim.adaptiveResetInterval=interval;if(interval!==before)log(`Adaptive clean starts relaxed: full grid reset every ${interval} PPO updates.`);return interval}
function effectiveResetInterval(metrics){if(sim.resetMode==='never')return Infinity;if(sim.resetMode==='adaptive')return adaptiveResetCadence(metrics);return clamp(Number(sim.resetMode)||1,1,8)}
async function performLearningUpdate(){
  sim.learning=true;sim.running=false;sim.physicsAcc=0;sim.decisionAcc=0;$('learningOverlay').classList.add('show');$('phaseText').textContent='BACKPROP';$('learningText').textContent=`Training on ${sim.experience} experiences…`;updateUI();await new Promise(r=>setTimeout(r,90));
  const ppoStarted=performance.now(),batch=buildTrainingBatch(),avgReward=sim.batchReward/Math.max(1,sim.experience);let loss=0,count=0;for(let epoch=0;epoch<sim.ppoEpochs;epoch++){shuffle(batch);for(const e of batch){loss+=trainSample(e,sim.ppoLearningRate);count++}$('learningText').textContent=`Backprop pass ${epoch+1}/${sim.ppoEpochs} · ${batch.length} samples`;await new Promise(r=>setTimeout(r,0))}
  sim.lastPpoMs=performance.now()-ppoStarted;sim.ppoTotalMs+=sim.lastPpoMs;sim.ppoCount++;sim.lastLoss=loss/Math.max(1,count);sim.update++;sim.temperature=Math.max(.72,1.35-sim.update*.005);const metrics=captureBatchMetrics(avgReward),resetInterval=effectiveResetInterval(metrics);sim.updatesSinceGridReset++;const fullGridReset=Number.isFinite(resetInterval)&&sim.updatesSinceGridReset>=resetInterval;metrics.resetInterval=Number.isFinite(resetInterval)?resetInterval:null;metrics.fullGridReset=fullGridReset;
  log(`Update ${sim.update}: avg run ${metrics.avgRunDistance.toFixed(0)}m · best ${metrics.batchBestRunDistance.toFixed(0)}m · PPO ${sim.lastPpoMs.toFixed(0)}ms · laps ${metrics.laps} · r/exp ${metrics.rewardPerExp.toFixed(3)} · ${fullGridReset?'clean grid reset':resetInterval===Infinity?'continue · no scheduled grid reset':`continue · reset in ${resetInterval-sim.updatesSinceGridReset} update${resetInterval-sim.updatesSinceGridReset===1?'':'s'}`}`);if(typeof sessionAfterLearningUpdate==='function')sessionAfterLearningUpdate(metrics);
  drivers.forEach(c=>{c.rollout=[];c.lastObs=null;c.lastForward=null;c.pendingReward=0;c.pendingDone=false});sim.experience=0;resetBatchTelemetry();if(fullGridReset){resetGrid();sim.updatesSinceGridReset=0}drivers.forEach(chooseAction);const resume=!sim.pauseAfterLearning;sim.pauseAfterLearning=false;sim.learning=false;sim.running=resume;$('learningOverlay').classList.remove('show');updateUI();
}
