// Clipped PPO backpropagation plus learning-contract diagnostics and experience-based schedules.
function preUpdateDiagnostics(batch){
  if(!batch.length)return{policyEntropy:0,valueRmse:0,explainedVariance:0};
  let entropy=0,valueSq=0,retMean=0;for(const e of batch){entropy+=Number(e.entropy)||0;const error=e.ret-e.value;valueSq+=error*error;retMean+=e.ret}retMean/=batch.length;
  let retVar=0,errorMean=0;for(const e of batch)errorMean+=e.ret-e.value;errorMean/=batch.length;let errorVar=0;for(const e of batch){const rd=e.ret-retMean,ed=(e.ret-e.value)-errorMean;retVar+=rd*rd;errorVar+=ed*ed}retVar/=batch.length;errorVar/=batch.length;
  return{policyEntropy:entropy/batch.length,valueRmse:Math.sqrt(valueSq/batch.length),explainedVariance:retVar>1e-9?1-errorVar/retVar:0};
}
function bootstrapValueForCar(car){const last=car.rollout.at(-1);if(!last||last.done)return 0;const obs=captureObservation(car),out=forward(obs,explorationTemperatureForExperience(sim.totalExperience));return Number(out.value)||0}
function buildTrainingBatch(){
  const batch=[];for(const car of activeDrivers()){let nextValue=bootstrapValueForCar(car),gae=0;for(let i=car.rollout.length-1;i>=0;i--){const e=car.rollout[i],mask=e.done?0:1,delta=e.reward+GAMMA*nextValue*mask-e.value;gae=delta+GAMMA*GAE_LAMBDA*mask*gae;e.adv=gae;e.ret=e.value+gae;nextValue=e.value}batch.push(...car.rollout)}
  let mean=0;for(const e of batch)mean+=e.adv;mean/=Math.max(1,batch.length);let variance=0;for(const e of batch){const d=e.adv-mean;variance+=d*d}variance/=Math.max(1,batch.length);const sd=Math.sqrt(variance)+1e-6;for(const e of batch)e.adv=(e.adv-mean)/sd;
  return{batch,diagnostics:preUpdateDiagnostics(batch)};
}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=(experimentRandom('shuffle')*(i+1))|0;[a[i],a[j]]=[a[j],a[i]]}}
function trainSample(e,lr){
  const temperature=Math.max(.1,Number(e.temperature)||sim.temperature),out=forward(e.obs,temperature),last=out.hidden.at(-1),newLog=Math.log(Math.max(1e-7,out.probs[e.action])),logRatio=clamp(newLog-e.logp,-10,10),ratio=Math.exp(logRatio),clipHit=Math.abs(ratio-1)>sim.ppoClip,objectiveClipped=(e.adv>=0&&ratio>1+sim.ppoClip)||(e.adv<0&&ratio<1-sim.ppoClip),dLogP=objectiveClipped?0:-e.adv*ratio/temperature,dLogits=new Float32Array(ACTIONS);
  for(let a=0;a<ACTIONS;a++)dLogits[a]=clamp(dLogP*((a===e.action?1:0)-out.probs[a]),-3,3);const dValue=clamp(.35*(out.value-e.ret),-3,3);
  let grad=new Float32Array(last.length);for(let j=0;j<last.length;j++){let g=net.value.w[j]*dValue;for(let a=0;a<ACTIONS;a++)g+=net.policy.w[a*last.length+j]*dLogits[a];grad[j]=g}
  const deltas=new Array(net.layers.length);for(let l=net.layers.length-1;l>=0;l--){const layer=net.layers[l],act=out.hidden[l],dz=new Float32Array(layer.outputSize);for(let j=0;j<layer.outputSize;j++)dz[j]=clamp(grad[j]*(1-act[j]*act[j]),-3,3);deltas[l]=dz;if(l>0){const prev=new Float32Array(layer.inputSize);for(let j=0;j<layer.outputSize;j++){const g=dz[j],row=j*layer.inputSize;for(let i=0;i<layer.inputSize;i++)prev[i]+=layer.w[row+i]*g}grad=prev}}
  for(let a=0;a<ACTIONS;a++){const base=a*last.length,g=dLogits[a];for(let j=0;j<last.length;j++)net.policy.w[base+j]-=lr*g*last[j];net.policy.b[a]-=lr*g}for(let j=0;j<last.length;j++)net.value.w[j]-=lr*dValue*last[j];net.value.b-=lr*dValue;
  for(let l=0;l<net.layers.length;l++){const layer=net.layers[l],input=l===0?e.obs:out.hidden[l-1],dz=deltas[l];for(let j=0;j<layer.outputSize;j++){const row=j*layer.inputSize,g=dz[j];for(let i=0;i<layer.inputSize;i++)layer.w[row+i]-=lr*g*input[i];layer.b[j]-=lr*g}}
  const policyLoss=-Math.min(ratio*e.adv,clamp(ratio,1-sim.ppoClip,1+sim.ppoClip)*e.adv),valueLoss=.5*(out.value-e.ret)*(out.value-e.ret),approxKl=(ratio-1)-logRatio;return{loss:policyLoss+.35*valueLoss,approxKl,clipHit};
}
function captureBatchMetrics(avgReward,preDiagnostics,ppoDiagnostics){
  const cars=activeDrivers(),liveDistances=cars.map(c=>c.episodePeakProgress),distanceSum=sim.batchEpisodeDistance+liveDistances.reduce((a,b)=>a+b,0),distanceCount=sim.batchEpisodes+cars.length,avgRunDistance=distanceSum/Math.max(1,distanceCount),batchBestRunDistance=Math.max(sim.batchBestRunDistance,...liveDistances,0);sim.bestRunDistance=Math.max(sim.bestRunDistance,batchBestRunDistance);
  const avgLapTime=sim.batchLapTimeCount>0?sim.batchLapTimeTotal/sim.batchLapTimeCount:null,bestLapTime=sim.batchBestLapTime>0?sim.batchBestLapTime:null,metrics={update:sim.update,seed:sim.experimentSeed,trackId:sim.trackMode,trackMirror:!!sim.trackMirror,observationCameraMode:normalizedObservationCameraMode(sim.observationCameraMode),resetMode:sim.resetMode,trainingDriverCount:cars.length,trainingCarCollisions:!!sim.trainingCarCollisions,trainingStaggered:!!sim.trainingStaggered,autoTrackSwitch:!!sim.autoTrackSwitch,trackSwitchEveryExperiences:sim.trackSwitchEveryExperiences,batchExperiences:sim.experience,trackLayoutVersion:TRACK_LAYOUT_VERSION,vehicleDynamicsVersion:VEHICLE_DYNAMICS_VERSION,vehicleObservationVersion:VEHICLE_OBSERVATION_VERSION,rewardContractVersion:REWARD_CONTRACT_VERSION,trainerVersion:TRAINER_VERSION,rewardPerExp:avgReward,forwardPerExp:sim.batchForwardMeters/Math.max(1,sim.experience),roadForwardMeters:sim.batchRoadForwardMeters,shoulderForwardMeters:sim.batchShoulderForwardMeters,grassForwardMeters:sim.batchGrassForwardMeters,backwardMeters:sim.batchBackwardMeters,offRoadPct:sim.batchOffRoadSeconds/Math.max(.001,sim.batchDriverSeconds)*100,noProgressPct:sim.batchNoProgressSeconds/Math.max(.001,sim.batchDriverSeconds)*100,avgRunDistance,batchBestRunDistance,bestRunDistance:sim.bestRunDistance,resets:sim.batchResets,laps:sim.batchLaps,avgLapTime,bestLapTime,lapTimeCount:sim.batchLapTimeCount,collisions:sim.collisions,collisionsPer1k:sim.collisions/Math.max(1,sim.experience)*1000,rewardBreakdown:{progress:sim.batchProgressReward,lapCompletion:sim.batchLapCompletionReward,surface:sim.batchSurfacePenalty,collision:sim.batchCollisionPenalty,terminal:sim.batchTerminalPenalty},policyEntropy:preDiagnostics.policyEntropy,valueRmse:preDiagnostics.valueRmse,explainedVariance:preDiagnostics.explainedVariance,approxKl:ppoDiagnostics.approxKl,clipFraction:ppoDiagnostics.clipFraction,temperature:sim.temperature,loss:sim.lastLoss,ppoMs:sim.lastPpoMs,avgPpoMs:sim.ppoCount?sim.ppoTotalMs/sim.ppoCount:0,ppo:ppoSettingsSnapshot(),totalExperience:sim.totalExperience,wallSeconds:sim.trainingWallSeconds,simSeconds:sim.trainingSimSeconds,steer:[...sim.batchSteerCounts],throttle:[...sim.batchThrottleCounts]};sim.lastMetrics=metrics;sim.history.push(metrics);return metrics;
}
function adaptiveResetCadence(metrics){const lapsWorth=metrics.avgRunDistance/Math.max(1,trackLength),before=sim.adaptiveResetInterval;let interval=before;if(interval===1&&lapsWorth>=.45)interval=2;else if(interval===2&&lapsWorth>=.90)interval=4;else if(interval===4&&lapsWorth>=1.80)interval=8;sim.adaptiveResetInterval=interval;if(interval!==before)log(`Adaptive clean-start budget relaxed to every ${cleanResetExperienceInterval(interval).toLocaleString()} experiences.`);return interval}
function effectiveResetMultiplier(metrics){if(sim.resetMode==='never')return Infinity;if(sim.resetMode==='adaptive')return adaptiveResetCadence(metrics);return clamp(Number(sim.resetMode)||1,1,8)}
function nextTrainingTrackId(){const ids=Object.keys(TRACK_DEFS),index=Math.max(0,ids.indexOf(sim.trackMode));return ids[(index+1)%ids.length]}
function shouldRotateTrainingTrack(collectedExperiences){sim.experiencesSinceTrackSwitch+=collectedExperiences;if(!sim.autoTrackSwitch)return false;const interval=Math.max(1,Number(sim.trackSwitchEveryExperiences)||TRACK_SWITCH_EXPERIENCES);if(sim.experiencesSinceTrackSwitch<interval)return false;sim.experiencesSinceTrackSwitch%=interval;return true}
async function performLearningUpdate(){
  sim.learning=true;sim.running=false;sim.physicsAcc=0;sim.decisionAcc=0;$('learningOverlay').classList.add('show');$('phaseText').textContent='BACKPROP';$('learningText').textContent=`Training on ${sim.experience} experiences…`;updateUI();await new Promise(r=>setTimeout(r,90));
  const collectedExperiences=sim.experience,ppoStarted=performance.now(),built=buildTrainingBatch(),batch=built.batch,avgReward=sim.batchReward/Math.max(1,sim.experience);let loss=0,count=0,klSum=0,clipCount=0;for(let epoch=0;epoch<sim.ppoEpochs;epoch++){shuffle(batch);for(const e of batch){const sample=trainSample(e,sim.ppoLearningRate);loss+=sample.loss;klSum+=sample.approxKl;if(sample.clipHit)clipCount++;count++}$('learningText').textContent=`Backprop pass ${epoch+1}/${sim.ppoEpochs} · ${batch.length} samples`;await new Promise(r=>setTimeout(r,0))}
  sim.lastPpoMs=performance.now()-ppoStarted;sim.ppoTotalMs+=sim.lastPpoMs;sim.ppoCount++;sim.lastLoss=loss/Math.max(1,count);sim.update++;sim.temperature=explorationTemperatureForExperience(sim.totalExperience);const ppoDiagnostics={approxKl:klSum/Math.max(1,count),clipFraction:clipCount/Math.max(1,count)},metrics=captureBatchMetrics(avgReward,built.diagnostics,ppoDiagnostics),resetMultiplier=effectiveResetMultiplier(metrics),resetInterval=cleanResetExperienceInterval(resetMultiplier);sim.experiencesSinceGridReset+=collectedExperiences;const fullGridReset=Number.isFinite(resetInterval)&&sim.experiencesSinceGridReset>=resetInterval,rotateTrack=shouldRotateTrainingTrack(collectedExperiences);metrics.resetIntervalExperiences=Number.isFinite(resetInterval)?resetInterval:null;metrics.fullGridReset=fullGridReset;
  const remaining=Number.isFinite(resetInterval)?Math.max(0,resetInterval-sim.experiencesSinceGridReset):Infinity;log(`Update ${sim.update}: avg run ${metrics.avgRunDistance.toFixed(0)}m · best ${metrics.batchBestRunDistance.toFixed(0)}m · PPO ${sim.lastPpoMs.toFixed(0)}ms · laps ${metrics.laps}${metrics.bestLapTime?` · best lap ${metrics.bestLapTime.toFixed(1)}s`:''} · r/exp ${metrics.rewardPerExp.toFixed(3)} · KL ${metrics.approxKl.toFixed(4)} · ${rotateTrack?'track rotation':fullGridReset?'clean grid reset':resetInterval===Infinity?'continue · failures only':`continue · ${remaining.toLocaleString()} exp to clean reset`}`);if(typeof sessionAfterLearningUpdate==='function')sessionAfterLearningUpdate(metrics);
  drivers.forEach(c=>{c.rollout=[];c.lastObs=null;c.lastForward=null;c.pendingReward=0;c.pendingDone=false});sim.experience=0;resetBatchTelemetry();if(rotateTrack){const next=nextTrainingTrackId();sim.trackMode=next;sim.experiencesSinceGridReset=0;resetRecentTelemetry();buildTrack(next,sim.trackMirror);resetGrid();primeObservations();if($('trackSelect'))$('trackSelect').value=next;log(`Auto-switched training to ${trackVariantName(next,sim.trackMirror)} after ${Number(sim.trackSwitchEveryExperiences).toLocaleString()} experiences.`);if(typeof sessionRecordTrackChange==='function')sessionRecordTrackChange(next)}else if(fullGridReset){sim.experiencesSinceGridReset%=resetInterval;resetGrid();primeObservations()}activeDrivers().forEach(chooseAction);const resume=!sim.pauseAfterLearning;sim.pauseAfterLearning=false;sim.learning=false;sim.running=resume;$('learningOverlay').classList.remove('show');updateUI();
}
