// Spectator camera, learning telemetry, progress charts, driver cards, and UI rendering.
function updateMainCamera(){const car=drivers[sim.selected],f=new THREE.Vector3(Math.cos(car.heading),0,Math.sin(car.heading)),roadY=surfaceHeightForCar(car);if(sim.cameraMode==='chase'){const desired=new THREE.Vector3(car.x-f.x*7,roadY+3.7,car.z-f.z*7);mainCamera.position.lerp(desired,.10);mainCamera.lookAt(car.x+f.x*5,roadY+.65,car.z+f.z*5)}else{mainCamera.position.set(car.x+f.x*.25,roadY+1.25,car.z+f.z*.25);mainCamera.lookAt(car.x+f.x*14,roadY+.65,car.z+f.z*14)}}
function resize(){const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h,false);mainCamera.aspect=w/h;mainCamera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();
function log(text){const el=$('log'),line=document.createElement('div');line.textContent=text;el.prepend(line);while(el.children.length>28)el.lastChild.remove()}
function formatDuration(seconds){seconds=Math.max(0,Math.floor(seconds||0));const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return h?`${h}h ${String(m).padStart(2,'0')}m`:m?`${m}m ${String(s).padStart(2,'0')}s`:`${s}s`}
function pctProgress(car){return mod(car.trackIndex-finishIndex,TRACK_N)/TRACK_N}
function updateDriversUI(){
  const wrap=$('drivers');wrap.innerHTML='';drivers.forEach((c,i)=>{const d=document.createElement('div');d.className='driver'+(i===sim.selected?' active':'');const status=sim.mode==='race'?(c.finishPlace!=null?`P${c.finishPlace} · ${c.finishTime.toFixed(1)}s`:c.raceStatus==='dnf'?'DNF':`lap ${Math.min(c.lap+1,sim.raceLaps)}/${sim.raceLaps}`):`${c.lap} lap${c.lap===1?'':'s'}`;d.innerHTML=`<div class="driver-head"><strong>Driver ${i+1}</strong><span>${status}</span></div><canvas class="driver-pov" width="32" height="20" aria-label="Driver ${i+1} neural camera input"></canvas><div class="mini"><span>speed <b>${c.speed.toFixed(1)}</b></span><span>ep reward <b>${c.episodeReward.toFixed(1)}</b></span><span>run <b>${c.episodePeakProgress.toFixed(0)}m</b></span><span>hits <b>${c.collisions}</b></span><span>passes <b>${c.overtakes}</b></span><span>gear <b>G${c.gear}</b></span></div><div class="damage"><div style="width:${c.damage}%"></div></div>`;d.addEventListener('click',()=>{sim.selected=i;updateUI()});wrap.appendChild(d);drawPreview(d.querySelector('.driver-pov'),c.latestRGBA)})
}
function actionName(car){return{steer:car.actionSteer<-.75?'HARD LEFT':car.actionSteer<-.1?'LEFT':car.actionSteer>.75?'HARD RIGHT':car.actionSteer>.1?'RIGHT':'STRAIGHT',throttle:car.actionThrottle>0?'THROTTLE':car.actionThrottle<0?'BRAKE':'COAST'}}
function currentMetrics(){
  if(sim.lastMetrics&&Number.isFinite(sim.lastMetrics.avgRunDistance))return sim.lastMetrics;const live=drivers.map(c=>c.episodePeakProgress),sum=sim.batchEpisodeDistance+live.reduce((a,b)=>a+b,0),count=sim.batchEpisodes+DRIVER_COUNT,batchBest=Math.max(sim.batchBestRunDistance,...live);
  return{rewardPerExp:sim.batchReward/Math.max(1,sim.experience),forwardPerExp:sim.batchForwardMeters/Math.max(1,sim.experience),offRoadPct:sim.batchOffRoadSeconds/Math.max(.001,sim.batchDriverSeconds)*100,avgRunDistance:sum/Math.max(1,count),batchBestRunDistance:batchBest,bestRunDistance:Math.max(sim.bestRunDistance,batchBest),resets:sim.batchResets,laps:sim.batchLaps,collisions:sim.collisions,totalExperience:sim.totalExperience,wallSeconds:sim.trainingWallSeconds,simSeconds:sim.trainingSimSeconds,steer:sim.batchSteerCounts,throttle:sim.batchThrottleCounts}
}
function drawProgressChart(){
  const canvas=$('learningChart');if(!canvas)return;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,padL=36,padR=8,padT=10,padB=20;ctx.clearRect(0,0,w,h);ctx.fillStyle='#08131d';ctx.fillRect(0,0,w,h);
  const history=sim.history.slice(-100).filter(x=>Number.isFinite(x.avgRunDistance));if(history.length<2){ctx.fillStyle='#718493';ctx.font='10px system-ui';ctx.fillText('Driving-distance history appears after learning updates.',12,h/2);return}
  const maxY=Math.max(10,...history.flatMap(x=>[Number(x.avgRunDistance)||0,Number(x.batchBestRunDistance)||0]))*1.08,x=i=>padL+i/(history.length-1)*(w-padL-padR),y=v=>padT+(1-v/maxY)*(h-padT-padB);
  ctx.strokeStyle='rgba(255,255,255,.10)';ctx.lineWidth=1;for(let k=0;k<=4;k++){const yy=padT+k/4*(h-padT-padB);ctx.beginPath();ctx.moveTo(padL,yy);ctx.lineTo(w-padR,yy);ctx.stroke();ctx.fillStyle='#718493';ctx.font='9px system-ui';ctx.fillText(`${Math.round(maxY*(1-k/4))}m`,3,yy+3)}
  const draw=(key,color)=>{ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();history.forEach((m,i)=>{const v=Number(m[key])||0;i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v))});ctx.stroke()};draw('avgRunDistance','#55dbea');draw('batchBestRunDistance','#ffd166');
  ctx.fillStyle='#718493';ctx.font='9px system-ui';ctx.fillText(`update ${history[0].update}`,padL,h-5);const lastLabel=`${history.at(-1).update}`;ctx.fillText(lastLabel,w-padR-ctx.measureText(lastLabel).width,h-5);ctx.fillStyle='#55dbea';ctx.fillText('avg run',padL+4,12);ctx.fillStyle='#ffd166';ctx.fillText('best run',padL+56,12)
}
function actionMixText(metrics){const steerTotal=metrics.steer.reduce((a,b)=>a+b,0)||1,driveTotal=metrics.throttle.reduce((a,b)=>a+b,0)||1,pct=(n,t)=>Math.round(n/t*100);return `Steer: L ${pct(metrics.steer[0]+metrics.steer[1],steerTotal)}% · straight ${pct(metrics.steer[2],steerTotal)}% · R ${pct(metrics.steer[3]+metrics.steer[4],steerTotal)}%  |  Drive: brake ${pct(metrics.throttle[0],driveTotal)}% · coast ${pct(metrics.throttle[1],driveTotal)}% · throttle ${pct(metrics.throttle[2],driveTotal)}%`}
function updateUI(){
  const headless=headlessActive();$('phaseText').textContent=sim.learning?'BACKPROP':sim.running?(sim.mode==='race'?'EVAL RACE':headless?'HEADLESS LEARN':'LEARNING'):'PAUSED';$('updateText').textContent=sim.update;$('experienceText').textContent=sim.mode==='race'?'frozen':`${sim.experience} / ${BATCH_TARGET}`;$('selectedText').textContent=`Driver ${sim.selected+1}`;$('trackText').textContent=TRACK_DEFS[activeTrackId]?.name||activeTrackId;$('actualSpeed').textContent=`${sim.achievedSpeed.toFixed(1)}×`;$('expLabel').textContent=sim.mode==='race'?'frozen':`${sim.experience} / ${BATCH_TARGET}`;$('expBar').style.width=sim.mode==='race'?'0%':`${Math.min(100,sim.experience/BATCH_TARGET*100)}%`;
  const metrics=currentMetrics(),liveBest=Math.max(0,...drivers.map(c=>c.episodePeakProgress)),bestEver=Math.max(Number(metrics.bestRunDistance)||0,sim.bestRunDistance,liveBest);$('rewardPerExp').textContent=sim.mode==='race'?'—':metrics.rewardPerExp.toFixed(3);$('avgRunDistance').textContent=sim.mode==='race'?'—':`${metrics.avgRunDistance.toFixed(0)}m`;$('batchBestRun').textContent=sim.mode==='race'?'—':`${metrics.batchBestRunDistance.toFixed(0)}m`;$('bestRunDistance').textContent=`${bestEver.toFixed(0)}m`;$('offRoadPct').textContent=sim.mode==='race'?'—':`${metrics.offRoadPct.toFixed(0)}%`;$('resetCount').textContent=sim.mode==='race'?'—':metrics.resets;$('totalExperience').textContent=sim.totalExperience.toLocaleString();$('trainingTime').textContent=formatDuration(sim.trainingWallSeconds);$('simTrainingTime').textContent=formatDuration(sim.trainingSimSeconds);$('actionMix').textContent=actionMixText(metrics);
  const car=drivers[sim.selected],names=actionName(car);$('steerOut').textContent=names.steer;$('throttleOut').textContent=names.throttle;$('confidenceOut').textContent=car.lastProb?`${Math.round(car.lastProb*100)}%`:'—';$('slipOut').textContent=`G${car.gear}`;
  $('runBtn').textContent=sim.mode==='race'?(sim.running?'Ⅱ Pause race':'▶ Resume race'):(sim.running?'Ⅱ Pause learning':'▶ Start learning');$('learnBtn').classList.toggle('primary',sim.mode==='learn');$('raceBtn').classList.toggle('primary',sim.mode==='race'&&!sim.raceFinished);$('headlessBtn').classList.toggle('primary',sim.headless);$('headlessBtn').textContent=sim.headless?'⚡ Headless ON':'⚡ Headless training';if(sim.mode==='race'&&!sim.raceFinished)$('raceResult').innerHTML=`<strong>Race on ${TRACK_DEFS[activeTrackId].name}:</strong> ${sim.raceLaps} laps · ${sim.raceTime.toFixed(1)} s · ${raceResultsText()}`;
  if(!headless){updateDriversUI();updatePOV();drawProgressChart()}
}
