// Spectator camera, mode UI, driver telemetry, dual progress charts, Brain Inspector, and Session Manager rendering.
let lastSessionListSig='',lastBrainLibrarySig='',lastTimelineSig='';
function updateMainCamera(){
  const car=drivers[sim.selected],f=new THREE.Vector3(Math.cos(car.heading),0,Math.sin(car.heading)),side=new THREE.Vector3(-f.z,0,f.x),roadY=surfaceHeightForCar(car),mode=sim.cameraMode;
  let desired,look;
  if(mode==='pov'){
    mainCamera.position.set(car.x+f.x*.25,roadY+1.25,car.z+f.z*.25);look=new THREE.Vector3(car.x+f.x*14,roadY+.65,car.z+f.z*14);
  }else if(mode==='high'){
    desired=new THREE.Vector3(car.x-f.x*12,roadY+11,car.z-f.z*12);mainCamera.position.lerp(desired,.08);look=new THREE.Vector3(car.x+f.x*7,roadY+.6,car.z+f.z*7);
  }else if(mode==='helicopter'){
    desired=new THREE.Vector3(car.x-f.x*16+side.x*9,roadY+20,car.z-f.z*16+side.z*9);mainCamera.position.lerp(desired,.045);look=new THREE.Vector3(car.x+f.x*6,roadY+.5,car.z+f.z*6);
  }else if(mode==='overhead'){
    desired=new THREE.Vector3(car.x-f.x*4,roadY+34,car.z-f.z*4);mainCamera.position.lerp(desired,.07);look=new THREE.Vector3(car.x+f.x*4,roadY,car.z+f.z*4);
  }else if(mode==='trackside'){
    const index=mod(car.trackIndex+trackStepsForDistance(28),TRACK_N),q=track[index],n=normals[index],height=q?.y||0;desired=new THREE.Vector3(q.x+n.x*(HALF_WIDTH+SHOULDER_WIDTH+4),height+3.8,q.z+n.z*(HALF_WIDTH+SHOULDER_WIDTH+4));mainCamera.position.lerp(desired,.10);look=new THREE.Vector3(car.x,roadY+.65,car.z);
  }else if(mode==='overview'){
    const span=Math.max(trackBounds.spanX,trackBounds.spanZ),height=Math.max(90,span*1.05);desired=new THREE.Vector3(trackBounds.centerX,height,trackBounds.centerZ+span*.10);mainCamera.position.lerp(desired,.08);look=new THREE.Vector3(trackBounds.centerX,(trackBounds.minY+trackBounds.maxY)/2,trackBounds.centerZ);
  }else{
    desired=new THREE.Vector3(car.x-f.x*7,roadY+3.7,car.z-f.z*7);mainCamera.position.lerp(desired,.10);look=new THREE.Vector3(car.x+f.x*5,roadY+.65,car.z+f.z*5);
  }
  mainCamera.lookAt(look);
}
function resize(){const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h,false);mainCamera.aspect=w/h;mainCamera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();
function log(text){const el=$('trainingLog'),line=document.createElement('div');line.textContent=text;el.prepend(line);while(el.children.length>28)el.lastChild.remove()}
function brainAveragePpoMs(brain){const t=brain?.training||{};if(Number(t.ppoCount)>0)return Number(t.ppoTotalMs||0)/Number(t.ppoCount);const timed=(t.history||[]).filter(x=>Number(x.ppoMs)>0);return timed.length?timed.reduce((s,x)=>s+Number(x.ppoMs),0)/timed.length:0}
function actionName(car){return{steer:car.actionSteer<-.75?'HARD LEFT':car.actionSteer<-.1?'LEFT':car.actionSteer>.75?'HARD RIGHT':car.actionSteer>.1?'RIGHT':'STRAIGHT',throttle:car.actionThrottle>0?'THROTTLE':car.actionThrottle<0?'BRAKE':'COAST'}}
function directionInfo(car){const a=car.directionAlignment;if(a<-.2)return{label:'WRONG WAY',cls:'warn'};if(a<.35)return{label:'ACROSS',cls:'caution'};return{label:`${Math.round(a*100)}% FWD`,cls:''}}
function updateDriversUI(){
  const wrap=$('driverCards');wrap.innerHTML='';
  activeDrivers().forEach((c,i)=>{
    const names=actionName(c),dir=directionInfo(c),d=document.createElement('div'),speedKmh=c.speed*3.6,slipDeg=c.slipAngle*180/Math.PI,yawDeg=c.yawRate*180/Math.PI;d.className='driver'+(i===sim.selected?' active':'');
    const lapStart=Number(c.lapStartedAt),lapElapsed=Math.max(0,sim.simClock-(Number.isFinite(lapStart)?lapStart:sim.simClock)),lapClock=`${lapElapsed.toFixed(1)}s`,lastLap=Number(c.lastLapTime)>0?`${c.lastLapTime.toFixed(1)}s`:'—';
    const status=sim.mode==='race'?(c.finishPlace!=null?`P${c.finishPlace} · ${c.finishTime.toFixed(1)}s`:c.raceStatus==='dnf'?'DNF':c.raceStatus==='ready'?'ready':`lap ${Math.min(c.lap+1,sim.raceLaps)}/${sim.raceLaps}`):`${c.lap} lap${c.lap===1?'':'s'}`;
    d.innerHTML=`<div class="driver-head"><strong>Driver ${i+1}</strong><span>${status}</span></div><canvas class="driver-pov" width="${OBS_W}" height="${OBS_H}" aria-label="Driver ${i+1} neural camera input"></canvas><div class="driver-actions"><div><small>Steering</small><b>${names.steer}</b></div><div><small>Drive</small><b>${names.throttle}</b></div><div><small>Gear</small><b>G${c.gear}</b></div><div><small>Engine</small><b>${Math.round(c.rpm).toLocaleString()} rpm</b></div></div><div class="mini"><span>speed <b>${speedKmh.toFixed(0)} km/h</b></span><span>slip <b class="${Math.abs(slipDeg)>12?'caution':''}">${slipDeg.toFixed(1)}°</b></span><span>yaw <b>${yawDeg.toFixed(0)}°/s</b></span><span>lateral <b>${c.lateralSpeed.toFixed(1)} m/s</b></span><span>run <b>${c.episodePeakProgress.toFixed(0)}m</b></span><span>lap clock <b>${lapClock}</b></span><span>last lap <b>${lastLap}</b></span><span>surface <b class="${c.surface==='road'?'':c.surface==='shoulder'?'caution':'warn'}">${c.surface}</b></span><span>direction <b class="${dir.cls}">${dir.label}</b></span><span>confidence <b>${c.lastProb?`${Math.round(c.lastProb*100)}%`:'—'}</b></span><span>damage <b>${c.damage.toFixed(0)}%</b></span><span>hits <b>${c.collisions}</b></span><span>ep reward <b>${c.episodeReward.toFixed(1)}</b></span><span>passes <b>${c.overtakes}</b></span></div><div class="damage"><div style="width:${c.damage}%"></div></div>`;
    d.addEventListener('click',()=>{sim.selected=i;updateUI();updateBrainInspector(true)});wrap.appendChild(d);drawPreview(d.querySelector('.driver-pov'),c.latestRGBA);
  });
}
function recordRecentTelemetry(dt){if(sim.mode!=='learn')return;sim.recentSampleAcc+=dt;if(sim.recentSampleAcc<.5)return;sim.recentSampleAcc%=.5;const t=sim.trainingSimSeconds;sim.recentHistory.push({t,trackId:sim.trackMode,trackMirror:!!sim.trackMirror,drivers:activeDrivers().map(c=>Math.max(0,c.episodePeakProgress))});const cutoff=t-60;while(sim.recentHistory.length&&sim.recentHistory[0].t<cutoff)sim.recentHistory.shift()}
function liveMetrics(){const cars=activeDrivers(),live=cars.map(c=>c.episodePeakProgress),sum=sim.batchEpisodeDistance+live.reduce((a,b)=>a+b,0),count=sim.batchEpisodes+cars.length,batchBest=Math.max(sim.batchBestRunDistance,...live,0),avgLapTime=sim.batchLapTimeCount>0?sim.batchLapTimeTotal/sim.batchLapTimeCount:null,bestLapTime=sim.batchBestLapTime>0?sim.batchBestLapTime:null;return{update:sim.update+sim.experience/sim.ppoBatchTarget,trackId:sim.trackMode,trackMirror:!!sim.trackMirror,resetMode:sim.resetMode,trainingDriverCount:cars.length,trainingCarCollisions:!!sim.trainingCarCollisions,trainingStaggered:!!sim.trainingStaggered,autoTrackSwitch:!!sim.autoTrackSwitch,trackSwitchEveryExperiences:sim.trackSwitchEveryExperiences,rewardPerExp:sim.batchReward/Math.max(1,sim.experience),forwardPerExp:sim.batchForwardMeters/Math.max(1,sim.experience),roadForwardMeters:sim.batchRoadForwardMeters,shoulderForwardMeters:sim.batchShoulderForwardMeters,grassForwardMeters:sim.batchGrassForwardMeters,backwardMeters:sim.batchBackwardMeters,offRoadPct:sim.batchOffRoadSeconds/Math.max(.001,sim.batchDriverSeconds)*100,noProgressPct:sim.batchNoProgressSeconds/Math.max(.001,sim.batchDriverSeconds)*100,avgRunDistance:sum/Math.max(1,count),batchBestRunDistance:batchBest,bestRunDistance:Math.max(sim.bestRunDistance,batchBest),resets:sim.batchResets,laps:sim.batchLaps,avgLapTime,bestLapTime,lapTimeCount:sim.batchLapTimeCount,collisions:sim.collisions,collisionsPer1k:sim.collisions/Math.max(1,sim.experience)*1000,rewardBreakdown:{progress:sim.batchProgressReward,surface:sim.batchSurfacePenalty,collision:sim.batchCollisionPenalty,terminal:sim.batchTerminalPenalty},totalExperience:sim.totalExperience,wallSeconds:sim.trainingWallSeconds,simSeconds:sim.trainingSimSeconds,steer:sim.batchSteerCounts,throttle:sim.batchThrottleCounts,live:true}}
function currentMetrics(){if(sim.lastMetrics&&Number.isFinite(sim.lastMetrics.avgRunDistance))return sim.lastMetrics;return liveMetrics()}
function chartPoints(){const completed=sim.history.filter(x=>Number.isFinite(x.avgRunDistance)),first=completed.find(x=>x.trackId)||{trackId:sim.trackMode,trackMirror:sim.trackMirror},points=[{update:0,trackId:first.trackId,trackMirror:!!first.trackMirror,avgRunDistance:0,batchBestRunDistance:0,bestRunDistance:0},...completed];if(sim.mode==='learn'&&sim.experience>0)points.push(liveMetrics());if(points.length<=500)return points;const sampled=[points[0]],stride=Math.ceil((points.length-2)/498);for(let i=1;i<points.length-1;i+=stride)sampled.push(points[i]);sampled.push(points.at(-1));return sampled}
function chartBase(canvas,emptyText){if(!canvas)return null;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,padL=42,padR=12,padT=18,padB=24;ctx.clearRect(0,0,w,h);ctx.fillStyle='#08131d';ctx.fillRect(0,0,w,h);return{ctx,w,h,padL,padR,padT,padB,empty:()=>{ctx.fillStyle='#718493';ctx.font='11px system-ui';ctx.fillText(emptyText,14,h/2)}}}
function drawRecentChart(){
  const base=chartBase($('recentChart'),'Recent driving appears after learning starts.');
  if(!base)return;
  const{ctx,w,h,padL,padR,padT,padB}=base,points=sim.recentHistory;
  if(points.length<2){base.empty();return}
  const lastT=points.at(-1).t,minT=Math.max(0,lastT-60),span=Math.max(1,lastT-minT),maxY=Math.max(10,...points.flatMap(p=>p.drivers))*1.08;
  const x=p=>padL+(p.t-minT)/span*(w-padL-padR),y=v=>padT+(1-v/maxY)*(h-padT-padB);
  ctx.strokeStyle='rgba(255,255,255,.10)';ctx.lineWidth=1;
  for(let k=0;k<=4;k++){
    const yy=padT+k/4*(h-padT-padB);ctx.beginPath();ctx.moveTo(padL,yy);ctx.lineTo(w-padR,yy);ctx.stroke();
    ctx.fillStyle='#718493';ctx.font='10px system-ui';ctx.fillText(`${Math.round(maxY*(1-k/4))}m`,4,yy+3);
  }
  const cols=['#55dbea','#ff7d88','#ffd166','#c8a5ff','#72e0a6','#ffa45b','#7fa8ff','#f28ee6','#b7dc5d','#e7e7e7'],count=Math.max(0,...points.map(p=>p.drivers?.length||0));
  for(let d=0;d<count;d++){
    ctx.strokeStyle=cols[d%cols.length];ctx.lineWidth=1.8;ctx.beginPath();
    points.forEach((p,i)=>{if(i)ctx.lineTo(x(p),y(p.drivers[d]||0));else ctx.moveTo(x(p),y(p.drivers[d]||0));});
    ctx.stroke();
  }
  ctx.fillStyle='#718493';ctx.font='10px system-ui';ctx.fillText(`-${Math.round(span)}s`,padL,h-6);ctx.fillText('now',w-padR-20,h-6);
  for(let i=0;i<count;i++){ctx.fillStyle=cols[i%cols.length];ctx.fillText(`D${i+1}`,padL+4+i*30,13)}
}
function drawTimelineChart(){const base=chartBase($('learningChart'),'Complete timeline begins as soon as training moves.');if(!base)return;const{ctx,w,h,padL,padR,padT,padB}=base,points=chartPoints();if(points.length<2){base.empty();return}const maxUpdate=Math.max(1,...points.map(m=>Number(m.update)||0)),maxY=Math.max(10,...points.flatMap(m=>[Number(m.avgRunDistance)||0,Number(m.batchBestRunDistance)||0]))*1.08,x=m=>padL+(Number(m.update)||0)/maxUpdate*(w-padL-padR),y=v=>padT+(1-v/maxY)*(h-padT-padB),variant=m=>`${m.trackId||''}:${m.trackMirror?'m':'n'}`;ctx.strokeStyle='rgba(255,255,255,.10)';ctx.lineWidth=1;for(let k=0;k<=4;k++){const yy=padT+k/4*(h-padT-padB);ctx.beginPath();ctx.moveTo(padL,yy);ctx.lineTo(w-padR,yy);ctx.stroke();ctx.fillStyle='#718493';ctx.font='10px system-ui';ctx.fillText(`${Math.round(maxY*(1-k/4))}m`,4,yy+3)}let previousVariant=variant(points[0]);for(let i=1;i<points.length;i++){const currentVariant=variant(points[i]);if(currentVariant!==previousVariant){const xx=x(points[i]);ctx.save();ctx.setLineDash([3,4]);ctx.strokeStyle='rgba(200,165,255,.48)';ctx.beginPath();ctx.moveTo(xx,padT);ctx.lineTo(xx,h-padB);ctx.stroke();ctx.restore();ctx.fillStyle='#c8a5ff';ctx.font='9px system-ui';ctx.fillText(trackVariantName(points[i].trackId,points[i].trackMirror),Math.min(xx+3,w-150),padT+10)}previousVariant=currentVariant}const draw=(key,color)=>{ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();points.forEach((m,i)=>{const v=Number(m[key])||0;i?ctx.lineTo(x(m),y(v)):ctx.moveTo(x(m),y(v))});ctx.stroke()};draw('avgRunDistance','#55dbea');draw('batchBestRunDistance','#ffd166');const last=points.at(-1);if(last?.live){ctx.fillStyle='#f4f7fb';ctx.beginPath();ctx.arc(x(last),y(last.avgRunDistance),3.5,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#718493';ctx.font='10px system-ui';ctx.fillText('update 0',padL,h-6);const lastLabel=`${maxUpdate.toFixed(maxUpdate<10?1:0)}`;ctx.fillText(lastLabel,w-padR-ctx.measureText(lastLabel).width,h-6);ctx.fillStyle='#55dbea';ctx.fillText('avg run',padL+4,13);ctx.fillStyle='#ffd166';ctx.fillText('best run',padL+66,13);if(last?.live){ctx.fillStyle='#f4f7fb';ctx.fillText('• live batch',padL+132,13)}}
function drawLapTimeChart(){const base=chartBase($('lapTimeChart'),'Completed lap times appear once a learner covers a full track length.');if(!base)return;const{ctx,w,h,padL,padR,padT,padB}=base,points=chartPoints(),timed=points.filter(m=>Number(m.avgLapTime)>0||Number(m.bestLapTime)>0);if(!timed.length){base.empty();return}const values=timed.flatMap(m=>[Number(m.avgLapTime),Number(m.bestLapTime)]).filter(v=>Number.isFinite(v)&&v>0),rawMin=Math.min(...values),rawMax=Math.max(...values),minY=Math.max(0,rawMin*.94),maxY=Math.max(minY+1,rawMax*1.06),maxUpdate=Math.max(1,...points.map(m=>Number(m.update)||0)),x=m=>padL+(Number(m.update)||0)/maxUpdate*(w-padL-padR),y=v=>padT+(v-minY)/(maxY-minY)*(h-padT-padB),variant=m=>`${m.trackId||''}:${m.trackMirror?'m':'n'}`;ctx.strokeStyle='rgba(255,255,255,.10)';ctx.lineWidth=1;for(let k=0;k<=4;k++){const value=minY+(maxY-minY)*k/4,yy=y(value);ctx.beginPath();ctx.moveTo(padL,yy);ctx.lineTo(w-padR,yy);ctx.stroke();ctx.fillStyle='#718493';ctx.font='10px system-ui';ctx.fillText(`${value.toFixed(0)}s`,4,yy+3)}let previousVariant=variant(points[0]);for(let i=1;i<points.length;i++){const currentVariant=variant(points[i]);if(currentVariant!==previousVariant){const xx=x(points[i]);ctx.save();ctx.setLineDash([3,4]);ctx.strokeStyle='rgba(200,165,255,.48)';ctx.beginPath();ctx.moveTo(xx,padT);ctx.lineTo(xx,h-padB);ctx.stroke();ctx.restore()}previousVariant=currentVariant}const draw=(key,color)=>{ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();let drawing=false,lastVariant=null;for(const m of points){const v=Number(m[key]),currentVariant=variant(m);if(!(Number.isFinite(v)&&v>0)){drawing=false;lastVariant=null;continue}if(drawing&&currentVariant===lastVariant)ctx.lineTo(x(m),y(v));else{ctx.moveTo(x(m),y(v));drawing=true}lastVariant=currentVariant}ctx.stroke()};draw('avgLapTime','#55dbea');draw('bestLapTime','#ffd166');ctx.fillStyle='#718493';ctx.font='10px system-ui';ctx.fillText('lower is better',padL,h-6);ctx.fillStyle='#55dbea';ctx.fillText('avg lap',padL+4,13);ctx.fillStyle='#ffd166';ctx.fillText('best lap',padL+62,13)}
function drawProgressCharts(){drawRecentChart();drawTimelineChart();drawLapTimeChart()}
function actionMixText(metrics){const steer=metrics.steer||[0,0,0,0,0],throttle=metrics.throttle||[0,0,0],steerTotal=steer.reduce((a,b)=>a+b,0)||1,driveTotal=throttle.reduce((a,b)=>a+b,0)||1,pct=(n,t)=>Math.round(n/t*100);return `Steer: L ${pct(steer[0]+steer[1],steerTotal)}% · straight ${pct(steer[2],steerTotal)}% · R ${pct(steer[3]+steer[4],steerTotal)}%  |  Drive: brake ${pct(throttle[0],driveTotal)}% · coast ${pct(throttle[1],driveTotal)}% · throttle ${pct(throttle[2],driveTotal)}%`}
function learningDiagnosticsText(metrics){const road=Number(metrics.roadForwardMeters)||0,shoulder=Number(metrics.shoulderForwardMeters)||0,grass=Number(metrics.grassForwardMeters)||0,total=road+shoulder+grass,pct=v=>total?Math.round(v/total*100):0,r=metrics.rewardBreakdown||{},ppo=Number.isFinite(Number(metrics.approxKl))?metrics:sim.lastMetrics||{},cars=Number(metrics.trainingDriverCount)||sim.trainingDriverCount,env=`${cars} car${cars===1?'':'s'} · ${metrics.trainingCarCollisions?'physical':'ghost'} · ${metrics.trainingStaggered?'staggered':'grid'} · ${metrics.trackMirror?'mirrored':'normal'} · ${metrics.autoTrackSwitch?'rotate':'fixed'}`;return `Env: ${env} | Forward surface: road ${pct(road)}% · shoulder ${pct(shoulder)}% · grass ${pct(grass)}% | backtrack ${(Number(metrics.backwardMeters)||0).toFixed(0)}m · no-progress ${(Number(metrics.noProgressPct)||0).toFixed(0)}% · hits/1k ${(Number(metrics.collisionsPer1k)||0).toFixed(1)} | reward Σ: progress ${(Number(r.progress)||0).toFixed(1)} · surface ${(Number(r.surface)||0).toFixed(1)} · collision ${(Number(r.collision)||0).toFixed(1)} · terminal ${(Number(r.terminal)||0).toFixed(1)} | PPO: H ${Number.isFinite(Number(ppo.policyEntropy))?Number(ppo.policyEntropy).toFixed(2):'—'} · KL ${Number.isFinite(Number(ppo.approxKl))?Number(ppo.approxKl).toFixed(4):'—'} · clip ${Number.isFinite(Number(ppo.clipFraction))?`${(Number(ppo.clipFraction)*100).toFixed(0)}%`:'—'} · value EV ${Number.isFinite(Number(ppo.explainedVariance))?Number(ppo.explainedVariance).toFixed(2):'—'}`}
function cleanResetText(){if(sim.resetMode==='never')return'failures only';const multiplier=sim.resetMode==='adaptive'?sim.adaptiveResetInterval:clamp(Number(sim.resetMode)||1,1,8),interval=cleanResetExperienceInterval(multiplier),remaining=Math.max(0,interval-sim.experiencesSinceGridReset);return`${sim.resetMode==='adaptive'?'adaptive · ':''}${interval.toLocaleString()} exp · ${remaining.toLocaleString()} left`}
function ppoSettingsText(settings=ppoSettingsSnapshot()){return`${settings.batchTarget} exp · ${settings.epochs} pass${settings.epochs===1?'':'es'} · lr ${settings.learningRate} · clip ${settings.clip}`}
function updateModeUI(){const learn=sim.mode==='learn';$('learnPanel').classList.toggle('hidden',!learn);$('racePanel').classList.toggle('hidden',learn);$('modeLearnBtn').classList.toggle('primary',learn);$('modeRaceBtn').classList.toggle('primary',!learn);$('modeHint').textContent=learn?'Collect experience and update the active brain with PPO.':'Freeze the active brain and measure how it drives without learning.';$('racePauseBtn').disabled=learn||sim.raceFinished;$('racePauseBtn').textContent=sim.running?'Ⅱ Pause race':'▶ Resume race'}
function trainedTracksText(brain){const variants=[...new Map((brain.trainingSegments||[]).map(s=>[`${s.trackId}:${s.trackMirror?'m':'n'}`,trackVariantName(s.trackId,s.trackMirror)])).values()];return variants.length?variants.join(', '):'not trained yet'}
function updateSessionUI(){if(!labSession)return;$('storageStatus').textContent=sessionStorageStatus;const active=activeBrain(),busy=sim.learning;if(document.activeElement!==$('sessionNameInput'))$('sessionNameInput').value=labSession.name||'';if(active&&document.activeElement!==$('brainNameInput'))$('brainNameInput').value=active.name||'';
  const info=browserStorageInfo||{},usage=info.usage==null?'unknown':formatBytes(info.usage),quota=info.quota==null?'unknown':formatBytes(info.quota);$('storageUsage').textContent=info.quota==null?usage:`${usage} / ${quota}`;$('storagePersistence').textContent=info.persisted===true?'persistent':info.persisted===false?'best effort':'unknown';const persistBtn=$('persistStorageBtn');persistBtn.disabled=info.persisted===true||!navigator.storage?.persist;persistBtn.textContent=info.persisted===true?'Persistent storage ✓':'Request persistent storage';
  for(const id of['loadSessionBtn','newSessionBtn','exportAllBtn','importAllBtn','renameSessionBtn','renameBrainBtn','duplicateBrainBtn','deleteSessionBtn','clearLocalDataBtn'])$(id).disabled=busy;
  const listSig=storedSessionSummaries.map(s=>`${s.id}:${s.name}:${s.updatedAt}:${s.brainCount}`).join('|');if(listSig!==lastSessionListSig){lastSessionListSig=listSig;const picker=$('sessionPicker'),wanted=labSession.id;picker.innerHTML=storedSessionSummaries.map(s=>`<option value="${escapeHtml(s.id)}">${escapeHtml(s.name)} · ${s.brainCount} brain${s.brainCount===1?'':'s'}</option>`).join('');if(storedSessionSummaries.some(s=>s.id===wanted))picker.value=wanted}
  const brainSig=labSession.brains.map(b=>`${b.id}:${b.name}:${b.updatedAt}:${b.config?.visionId}:${b.config?.networkId}:${b.training?.update||0}:${b.training?.totalExperience||0}:${b.training?.lastPpoMs||0}:${b.training?.ppoCount||0}:${JSON.stringify(b.training?.ppo||{})}:${b.races?.length||0}`).join('|')+`:${labSession.activeBrainId}:${busy}`;if(brainSig!==lastBrainLibrarySig){lastBrainLibrarySig=brainSig;const wrap=$('brainLibrary');wrap.innerHTML='';for(const brain of labSession.brains){const el=document.createElement('div'),isActive=brain.id===labSession.activeBrainId,params=parameterCountForConfig(brain.config),tensor=modelTensorBytesForConfig(brain.config),macs=forwardMacCountForConfig(brain.config),lastPpo=Number(brain.training?.lastPpoMs)||0,avgPpo=brainAveragePpoMs(brain),brainPpo=normalizedPpoSettings(brain.training?.ppo||PPO_DEFAULTS),canDelete=labSession.brains.length>1&&!busy;el.className=`brain-entry${isActive?' active':''}`;el.innerHTML=`<div class="brain-entry-head"><div><strong>${escapeHtml(brain.name)}</strong><div class="brain-entry-meta">${escapeHtml(brainConfigLabel(brain.config))}</div></div>${isActive?'<span class="chip">active</span>':''}</div><div class="brain-cost-grid"><span><small>Params</small><b>${compactNumber(params)}</b></span><span><small>Tensors</small><b>${formatBytes(tensor)}</b></span><span><small>Forward</small><b>${compactNumber(macs)} MAC</b></span><span><small>Last PPO</small><b>${formatMs(lastPpo)}</b></span><span><small>Avg PPO</small><b>${formatMs(avgPpo)}</b></span></div><div class="brain-entry-stats"><span>update <b>${brain.training?.update||0}</b></span><span>exp <b>${Number(brain.training?.totalExperience||0).toLocaleString()}</b></span><span>best <b>${Math.round(brain.training?.bestRunDistance||0)}m</b></span><span>races <b>${brain.races?.length||0}</b></span></div><div class="brain-entry-meta">trained: ${escapeHtml(trainedTracksText(brain))}</div><div class="brain-entry-meta">PPO: ${escapeHtml(ppoSettingsText(brainPpo))}</div><div class="brain-entry-actions">${isActive?'':`<button data-use-brain="${escapeHtml(brain.id)}"${busy?' disabled':''}>Use</button>`}<button data-export-brain="${escapeHtml(brain.id)}"${busy?' disabled':''}>Export</button><button class="danger" data-delete-brain="${escapeHtml(brain.id)}"${canDelete?'':' disabled'}>Delete</button></div>`;wrap.appendChild(el)}wrap.querySelectorAll('[data-use-brain]').forEach(btn=>btn.addEventListener('click',()=>switchActiveBrain(btn.dataset.useBrain).catch(error=>log(`Brain switch failed: ${error.message}`))));wrap.querySelectorAll('[data-export-brain]').forEach(btn=>btn.addEventListener('click',()=>exportBrainById(btn.dataset.exportBrain)));wrap.querySelectorAll('[data-delete-brain]').forEach(btn=>btn.addEventListener('click',()=>deleteBrain(btn.dataset.deleteBrain).catch(error=>log(`Brain delete failed: ${error.message}`))))}
  const events=[...(labSession.events||[])].slice(-14).reverse(),timelineSig=events.map(e=>e.id).join('|');if(timelineSig!==lastTimelineSig){lastTimelineSig=timelineSig;$('sessionTimeline').innerHTML=events.length?events.map(e=>`<div class="session-event">${escapeHtml(e.text)}<time>${escapeHtml(new Date(e.at).toLocaleString())}</time></div>`).join(''):'<div class="session-event">Session activity will appear here.</div>'}
}
function updateHeaderBrainUI(){$('visionChip').textContent=`${OBS_W}×${OBS_H} ${CHANNELS===3?'RGB':'gray'}`;$('brainChip').textContent=`${[INPUTS,...HIDDEN_LAYERS,ACTIONS].join('→')} + value`;$('seedChip').textContent=String(sim.experimentSeed);$('paramsChip').textContent=compactNumber(networkParameterCount());$('modelSizeChip').textContent=formatBytes(modelTensorBytesForConfig());if($('ppoChip'))$('ppoChip').textContent=`${sim.ppoBatchTarget} exp · ${sim.ppoEpochs}×`}
function updateDriverLegend(){const wrap=$('driverLegend');if(!wrap)return;const cols=['#55dbea','#ff7d88','#ffd166','#c8a5ff','#72e0a6','#ffa45b','#7fa8ff','#f28ee6','#b7dc5d','#e7e7e7'];wrap.innerHTML=activeDrivers().map((c,i)=>`<span><i class="dot" style="background:${cols[i%cols.length]}"></i>Driver ${i+1}</span>`).join('')}
function updateUI(){
  const cars=activeDrivers();if(sim.selected>=cars.length)sim.selected=0;const headless=headlessActive(),selected=drivers[sim.selected],dir=directionInfo(selected),learningActive=sim.mode==='learn'&&(sim.running||sim.learning);updateModeUI();updateHeaderBrainUI();updateDriverLegend();$('phaseText').textContent=sim.learning?'BACKPROP':sim.running?(sim.mode==='race'?'EVAL RACE':headless?'HEADLESS LEARN':'LEARNING'):sim.mode==='race'?'RACE SETUP':'PAUSED';$('updateText').textContent=sim.update;$('experienceText').textContent=sim.mode==='race'?'frozen':`${sim.experience} / ${sim.ppoBatchTarget}`;$('selectedText').textContent=`Driver ${sim.selected+1}`;$('trackText').textContent=trackVariantName(activeTrackId,activeTrackMirror);$('surfaceText').textContent=(selected.surface||'road').toUpperCase();$('surfaceText').className=selected.surface==='road'?'':selected.surface==='shoulder'?'caution':'warn';$('directionText').textContent=dir.label;$('directionText').className=dir.cls;if($('vehicleSpeedText'))$('vehicleSpeedText').textContent=`${Math.round(selected.speed*3.6)} km/h`;if($('slipText')){$('slipText').textContent=`${(selected.slipAngle*180/Math.PI).toFixed(1)}°`;$('slipText').className=Math.abs(selected.slipAngle)>.21?'caution':''}$('actualSpeed').textContent=`${sim.achievedSpeed.toFixed(1)}×`;$('expLabel').textContent=sim.mode==='race'?'frozen':`${sim.experience} / ${sim.ppoBatchTarget}`;$('expBar').style.width=sim.mode==='race'?'0%':`${Math.min(100,sim.experience/sim.ppoBatchTarget*100)}%`;
  const metrics=currentMetrics(),diagnosticMetrics=sim.mode==='learn'&&sim.experience>0?liveMetrics():metrics,liveBest=Math.max(0,...cars.map(c=>c.episodePeakProgress)),bestEver=Math.max(Number(metrics.bestRunDistance)||0,sim.bestRunDistance,liveBest);  if($('avgLapTime'))$('avgLapTime').textContent=sim.mode==='race'?'—':Number(metrics.avgLapTime)>0?`${Number(metrics.avgLapTime).toFixed(1)}s`:'—';if($('bestLapTime'))$('bestLapTime').textContent=sim.mode==='race'?'—':Number(metrics.bestLapTime)>0?`${Number(metrics.bestLapTime).toFixed(1)}s`:'—';
$('rewardPerExp').textContent=sim.mode==='race'?'—':Number(metrics.rewardPerExp||0).toFixed(3);$('avgRunDistance').textContent=sim.mode==='race'?'—':`${Number(metrics.avgRunDistance||0).toFixed(0)}m`;$('batchBestRun').textContent=sim.mode==='race'?'—':`${Number(metrics.batchBestRunDistance||0).toFixed(0)}m`;$('bestRunDistance').textContent=`${bestEver.toFixed(0)}m`;$('offRoadPct').textContent=sim.mode==='race'?'—':`${Number(metrics.offRoadPct||0).toFixed(0)}%`;$('resetCount').textContent=sim.mode==='race'?'—':Number(metrics.resets||0);$('totalExperience').textContent=sim.totalExperience.toLocaleString();$('trainingTime').textContent=formatDuration(sim.trainingWallSeconds);$('simTrainingTime').textContent=formatDuration(sim.trainingSimSeconds);$('lastPpoTime').textContent=formatMs(sim.lastPpoMs);$('avgPpoTime').textContent=formatMs(sim.ppoCount?sim.ppoTotalMs/sim.ppoCount:0);$('cleanResetStatus').textContent=sim.mode==='race'?'frozen':cleanResetText();$('actionMix').textContent=actionMixText(diagnosticMetrics);if($('learningDiagnostics'))$('learningDiagnostics').textContent=learningDiagnosticsText(diagnosticMetrics);$('runBtn').textContent=learningActive?'Ⅱ Pause learning':'▶ Start learning';$('headlessBtn').classList.toggle('primary',sim.headless);$('headlessBtn').textContent=sim.headless?'⚡ Headless visuals ON':'⚡ Headless visuals';$('raceBtn').textContent=sim.raceFinished?'🏁 Start evaluation race':'🏁 Restart evaluation race';if(sim.mode==='race'&&!sim.raceFinished)$('raceResult').innerHTML=`<strong>Race on ${TRACK_DEFS[activeTrackId].name}:</strong> ${sim.raceLaps} laps · ${sim.raceTime.toFixed(1)} s · ${raceResultsText()}`;updateSessionUI();drawProgressCharts();renderExperimentComparison();if(!headless){updateDriversUI();updateBrainInspector()}
}
